import { describe, it, expect, beforeEach, vi } from 'vitest';

const mockDbSelect = vi.hoisted(() => vi.fn());
const mockDbInsert = vi.hoisted(() => vi.fn());

vi.mock('@twicely/db', () => ({
  db: {
    select: mockDbSelect,
    insert: mockDbInsert,
  },
}));

vi.mock('@twicely/db/schema', () => ({
  conversation: {
    id: 'id',
    buyerId: 'buyer_id',
    orderId: 'order_id',
  },
  message: {
    id: 'id',
    conversationId: 'conversation_id',
    senderUserId: 'sender_user_id',
    body: 'body',
    isAutoGenerated: 'is_auto_generated',
  },
}));

vi.mock('@twicely/logger', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));

vi.mock('@paralleldrive/cuid2', () => ({
  createId: vi.fn().mockReturnValue('test-msg-id'),
}));

import { sendLocalAutoMessage } from '../local-auto-messages';
import { logger } from '@twicely/logger';

function makeSelectChain(resolveValue: unknown) {
  const chain = {
    from: vi.fn(),
    where: vi.fn(),
    limit: vi.fn().mockResolvedValue(resolveValue),
  };
  chain.from.mockReturnValue(chain);
  chain.where.mockReturnValue(chain);
  return chain;
}

function makeInsertChain() {
  return { values: vi.fn().mockResolvedValue([]) };
}

describe('sendLocalAutoMessage', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('inserts a message when conversation is found', async () => {
    const selectChain = makeSelectChain([{ id: 'conv-1', buyerId: 'buyer-1' }]);
    mockDbSelect.mockReturnValue(selectChain);

    const insertChain = makeInsertChain();
    mockDbInsert.mockReturnValue(insertChain);

    await sendLocalAutoMessage('order-1', 'BOTH_CHECKED_IN', {});

    expect(mockDbInsert).toHaveBeenCalled();
    expect(insertChain.values).toHaveBeenCalledWith(
      expect.objectContaining({
        conversationId: 'conv-1',
        isAutoGenerated: true,
      }),
    );
  });

  it('logs a warning and skips insert when conversation is not found', async () => {
    const selectChain = makeSelectChain([]);
    mockDbSelect.mockReturnValue(selectChain);

    await sendLocalAutoMessage('order-missing', 'BOTH_CHECKED_IN', {});

    expect(mockDbInsert).not.toHaveBeenCalled();
    expect(logger.warn).toHaveBeenCalled();
  });

  it('includes locationName in BOTH_CHECKED_IN message when provided', async () => {
    const selectChain = makeSelectChain([{ id: 'conv-2', buyerId: 'buyer-2' }]);
    mockDbSelect.mockReturnValue(selectChain);
    const insertChain = makeInsertChain();
    mockDbInsert.mockReturnValue(insertChain);

    await sendLocalAutoMessage('order-2', 'BOTH_CHECKED_IN', {
      locationName: 'Starbucks on Main St',
    });

    const callValues = insertChain.values.mock.calls[0]?.[0] as { body: string };
    expect(callValues?.body).toContain('Starbucks on Main St');
  });

  it('includes noShowParty in NO_SHOW message when provided', async () => {
    const selectChain = makeSelectChain([{ id: 'conv-3', buyerId: 'buyer-3' }]);
    mockDbSelect.mockReturnValue(selectChain);
    const insertChain = makeInsertChain();
    mockDbInsert.mockReturnValue(insertChain);

    await sendLocalAutoMessage('order-3', 'NO_SHOW', { noShowParty: 'Buyer' });

    const callValues = insertChain.values.mock.calls[0]?.[0] as { body: string };
    expect(callValues?.body).toContain('Buyer');
  });
});
