import { db } from '@twicely/db';
import { conversation, message as messageTable, user, listing } from '@twicely/db/schema';
import { eq } from 'drizzle-orm';
import { notify } from '@twicely/notifications/service';
import { logger } from '@twicely/logger';
import { publishToChannel } from '@twicely/realtime/centrifugo-publisher';
import { conversationChannel, MESSAGING_EVENTS } from '@twicely/realtime/messaging-channels';

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://twicely.co';

/**
 * Notify the recipient when a new message is sent.
 * Fire-and-forget: errors are logged but never thrown.
 */
export async function notifyNewMessage(messageId: string): Promise<void> {
  try {
    // Fetch message
    const [msg] = await db
      .select({
        id: messageTable.id,
        conversationId: messageTable.conversationId,
        senderUserId: messageTable.senderUserId,
        body: messageTable.body,
        isAutoGenerated: messageTable.isAutoGenerated,
      })
      .from(messageTable)
      .where(eq(messageTable.id, messageId))
      .limit(1);

    if (!msg || msg.isAutoGenerated) return;

    // Fetch conversation
    const [conv] = await db
      .select({
        buyerId: conversation.buyerId,
        sellerId: conversation.sellerId,
        listingId: conversation.listingId,
      })
      .from(conversation)
      .where(eq(conversation.id, msg.conversationId))
      .limit(1);

    if (!conv) return;

    // Determine recipient
    const recipientId = msg.senderUserId === conv.buyerId
      ? conv.sellerId
      : conv.buyerId;

    // Do not notify if sender is the recipient (should not happen but guard)
    if (recipientId === msg.senderUserId) return;

    // Fetch sender name
    const [sender] = await db
      .select({ name: user.name })
      .from(user)
      .where(eq(user.id, msg.senderUserId))
      .limit(1);

    // Fetch listing title (if conversation has a listing)
    let itemTitle = 'an item';
    if (conv.listingId) {
      const [listingRow] = await db
        .select({ title: listing.title })
        .from(listing)
        .where(eq(listing.id, conv.listingId))
        .limit(1);
      if (listingRow?.title) {
        itemTitle = listingRow.title;
      }
    }

    await notify(recipientId, 'messaging.new_message', {
      senderName: sender?.name ?? 'Someone',
      itemTitle,
      messagePreview: msg.body.slice(0, 200),
      conversationUrl: `${BASE_URL}/my/messages/${msg.conversationId}`,
    });

    // Publish to Centrifugo for real-time delivery — fire-and-forget
    publishToChannel(conversationChannel(msg.conversationId), {
      type: MESSAGING_EVENTS.NEW_MESSAGE,
      message: {
        id: msg.id,
        senderUserId: msg.senderUserId,
        senderName: sender?.name ?? 'Someone',
        body: msg.body,
        attachments: [],
        isRead: false,
        readAt: null,
        isAutoGenerated: false,
        createdAt: new Date().toISOString(),
      },
    }).catch(() => {});
  } catch (err) {
    logger.error('[notifyNewMessage] Error', { error: String(err) });
  }
}
