import type { TemplateDef } from '@twicely/notifications/templates';

/**
 * Notification templates for affiliate/influencer events (G3.1).
 */
export const AFFILIATE_TEMPLATES: Record<string, TemplateDef> = {
  'affiliate.influencer_application_received': {
    key: 'affiliate.influencer_application_received',
    name: 'Influencer Application Received',
    category: 'affiliate',
    priority: 'NORMAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'New influencer application from {{applicantName}}',
    bodyTemplate: '{{applicantName}} has submitted an influencer affiliate application. Review it at /usr/affiliates/{{affiliateId}}.',
  },
  'affiliate.influencer_approved': {
    key: 'affiliate.influencer_approved',
    name: 'Influencer Application Approved',
    category: 'affiliate',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your influencer application was approved!',
    bodyTemplate: 'Congratulations! Your Twicely influencer application has been approved. Your commission rate is {{commissionRate}} with a {{cookieDays}}-day attribution window.',
  },
  'affiliate.influencer_rejected': {
    key: 'affiliate.influencer_rejected',
    name: 'Influencer Application Rejected',
    category: 'affiliate',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your influencer application was not approved',
    bodyTemplate: 'Thank you for applying to the Twicely influencer program. After review, we are unable to approve your application at this time. You remain an active community affiliate and can reapply in the future.',
  },
  'affiliate.payout_sent': {
    key: 'affiliate.payout_sent',
    name: 'Affiliate Payout Sent',
    category: 'affiliate',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your affiliate payout of {{amountFormatted}} has been sent',
    bodyTemplate: 'Your affiliate commission payout of {{amountFormatted}} has been initiated via {{payoutMethod}}. Funds typically arrive within 1–3 business days.',
  },
  'affiliate.payout_failed': {
    key: 'affiliate.payout_failed',
    name: 'Affiliate Payout Failed',
    category: 'affiliate',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your affiliate payout could not be processed',
    bodyTemplate: 'We were unable to process your affiliate payout of {{amountFormatted}}. Reason: {{failedReason}}. Please check your payout settings and contact support if the issue persists.',
  },
  'affiliate.fraud_warning': {
    key: 'affiliate.fraud_warning',
    name: 'Affiliate Fraud Warning',
    category: 'affiliate',
    priority: 'HIGH',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'Your affiliate account has been flagged for suspicious activity',
    bodyTemplate: 'Your affiliate account has been flagged for suspicious activity: {{reason}}. This is warning {{warningNumber}} of 3. Continued violations may result in suspension or permanent ban.',
  },
  'affiliate.fraud_suspended': {
    key: 'affiliate.fraud_suspended',
    name: 'Affiliate Fraud Suspended',
    category: 'affiliate',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your affiliate account has been suspended',
    bodyTemplate: 'Your affiliate account has been suspended for 30 days due to repeated policy violations: {{reason}}. If you believe this is an error, contact support.',
  },
  'affiliate.fraud_banned': {
    key: 'affiliate.fraud_banned',
    name: 'Affiliate Fraud Banned',
    category: 'affiliate',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your affiliate account has been permanently banned',
    bodyTemplate: 'Your affiliate account has been permanently banned due to policy violations: {{reason}}. All pending commissions have been forfeited. If you believe this is an error, contact support.',
  },
  'affiliate.suspension_lifted': {
    key: 'affiliate.suspension_lifted',
    name: 'Affiliate Suspension Lifted',
    category: 'affiliate',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your affiliate account suspension has been lifted',
    bodyTemplate: '{{reason}}',
  },
};
