import type { TemplateDef } from '@twicely/notifications/templates';

/**
 * Notification templates for local meetup safety events (G2.6).
 */
export const LOCAL_TEMPLATES: Record<string, TemplateDef> = {
  'local.safety.nudge': {
    key: 'local.safety.nudge',
    name: 'Safety Check-In Nudge',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Check-in for your local meetup — order {{orderId}}',
    bodyTemplate:
      'Both parties checked in over 30 minutes ago but the sale has not been confirmed. If you need help, contact Twicely Support.',
  },
  'local.safety.escalated': {
    key: 'local.safety.escalated',
    name: 'Safety Escalation — Support Notified',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'A support team member has been notified — order {{orderId}}',
    bodyTemplate:
      'A support team member has been notified about your local meetup. You can also contact Twicely Support directly.',
  },
  'local.auto_cancel': {
    key: 'local.auto_cancel',
    name: 'Local Meetup Auto-Canceled',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your local meetup has been canceled — order {{orderId}}',
    bodyTemplate:
      'Your local meetup for order {{orderId}} was automatically canceled after 48 hours without completion. A support case has been opened.',
  },
  'local.schedule.proposal': {
    key: 'local.schedule.proposal',
    name: 'Meetup Time Proposed',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Meetup time proposed for your order',
    bodyTemplate: '{proposerName} proposed {date} at {time}. Tap to accept or suggest another time.',
  },
  'local.schedule.accepted': {
    key: 'local.schedule.accepted',
    name: 'Meetup Time Confirmed',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Meetup confirmed for {date} at {time}',
    bodyTemplate: 'Your meetup is confirmed for {date} at {time}. Check-in will be available when you arrive.',
  },
  'local.schedule.reminder_setup': {
    key: 'local.schedule.reminder_setup',
    name: 'Schedule Your Meetup',
    category: 'local',
    priority: 'NORMAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'Schedule your meetup',
    bodyTemplate: "Don't forget to schedule your meetup for {itemTitle}.",
  },
  'local.reschedule.proposal': {
    key: 'local.reschedule.proposal',
    name: 'Meetup Reschedule Proposed',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: '{name} wants to reschedule your meetup',
    bodyTemplate: '{name} wants to reschedule your meetup to {date} at {time}. Accept or decline.',
  },
  'local.reschedule.accepted': {
    key: 'local.reschedule.accepted',
    name: 'Meetup Reschedule Accepted',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Your reschedule request was accepted',
    bodyTemplate: 'Your reschedule request was accepted. Meetup now set for {date} at {time}.',
  },
  'local.reschedule.declined': {
    key: 'local.reschedule.declined',
    name: 'Meetup Reschedule Declined',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Your reschedule request was declined',
    bodyTemplate: 'Your reschedule request was declined. The meetup is still set for {date} at {time}.',
  },
  'local.cancel': {
    key: 'local.cancel',
    name: 'Local Meetup Canceled',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your local meetup has been canceled',
    bodyTemplate: 'The {canceledByParty} has canceled the local meetup for order {{orderId}}. A full refund has been issued.',
  },
  'local.dayof.request': {
    key: 'local.dayof.request',
    name: 'Day-of Meetup Confirmation Request',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Are you still on for today\'s meetup?',
    bodyTemplate: 'The buyer is confirming today\'s meetup at {time}. Confirm or reschedule.',
  },
  'local.dayof.confirmed': {
    key: 'local.dayof.confirmed',
    name: 'Seller Confirmed Day-of Meetup',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'Meetup confirmed for today',
    bodyTemplate: 'The seller confirmed they are coming to your meetup at {time}.',
  },
  'local.dayof.expired': {
    key: 'local.dayof.expired',
    name: 'Seller Did Not Confirm Meetup',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Seller did not confirm today\'s meetup',
    bodyTemplate: 'The seller did not respond to your day-of confirmation request. A reliability mark has been applied. You can still check in at the meetup location.',
  },
  'local.dayof.expired_seller': {
    key: 'local.dayof.expired_seller',
    name: 'Day-of Confirmation Expired (Seller Notice)',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'You missed the day-of meetup confirmation',
    bodyTemplate: 'You did not respond to the buyer\'s day-of confirmation request within the window. A reliability mark has been applied to your account.',
  },
  'local.reminder.24hr': {
    key: 'local.reminder.24hr',
    name: 'Meetup Reminder — 24 Hours',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Your meetup for {itemTitle} is tomorrow',
    bodyTemplate: 'Your meetup for {itemTitle} is tomorrow at {time} at {location}.',
  },
  'local.reminder.1hr': {
    key: 'local.reminder.1hr',
    name: 'Meetup Reminder — 1 Hour',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['IN_APP', 'EMAIL'],
    subjectTemplate: 'Your meetup for {itemTitle} is in 1 hour',
    bodyTemplate: 'Your meetup for {itemTitle} is in 1 hour. {location}.',
  },
  // G2.15 — Fraud Detection Notifications (template content deferred)
  'local.fraud.buyer_refund': {
    key: 'local.fraud.buyer_refund',
    name: 'SafeTrade Refund Issued',
    category: 'local',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your SafeTrade meetup has been canceled — full refund issued',
    bodyTemplate: 'Your local meetup has been canceled. A full refund has been issued to your payment method.',
  },
  'local.fraud.seller_flagged': {
    key: 'local.fraud.seller_flagged',
    name: 'Listing or Transaction Flagged',
    category: 'local',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your listing or transaction has been flagged for review',
    bodyTemplate: 'Your listing or transaction has been flagged for review by our trust and safety team.',
  },
  'local.fraud.seller_banned': {
    key: 'local.fraud.seller_banned',
    name: 'Local Transactions Suspended',
    category: 'local',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your local meetup access has been suspended',
    bodyTemplate: 'Due to a confirmed policy violation, your ability to participate in local meetups has been suspended.',
  },
  'local.fraud.seller_suspended': {
    key: 'local.fraud.seller_suspended',
    name: 'Account Suspended',
    category: 'local',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your account has been suspended',
    bodyTemplate: 'Your seller account has been suspended due to repeated policy violations. Contact support to appeal.',
  },
};
