import type { TemplateDef } from '@twicely/notifications/templates';

/**
 * Notification templates for post-order events: returns, disputes,
 * buyer protection, and shipping exceptions.
 */
export const POST_ORDER_TEMPLATES: Record<string, TemplateDef> = {
  'return.requested': {
    key: 'return.requested',
    name: 'Return Requested',
    category: 'returns',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Return requested for order {{orderNumber}}',
    bodyTemplate: 'A buyer has requested to return an item from order {{orderNumber}}. Reason: {{reason}}. Please respond within 3 business days.',
  },
  'return.approved': {
    key: 'return.approved',
    name: 'Return Approved',
    category: 'returns',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your return request has been approved',
    bodyTemplate: 'Your return request for order {{orderNumber}} has been approved. Please ship the item back within 7 days.',
  },
  'return.declined': {
    key: 'return.declined',
    name: 'Return Declined',
    category: 'returns',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your return request was not approved',
    bodyTemplate: 'Your return request for order {{orderNumber}} was not approved. Reason: {{declineReason}}. If you disagree, you can escalate to Twicely support.',
  },
  'return.shipped': {
    key: 'return.shipped',
    name: 'Return Shipped',
    category: 'returns',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Return shipment on the way for order {{orderNumber}}',
    bodyTemplate: 'The buyer has shipped the return for order {{orderNumber}}. Tracking: {{trackingNumber}}',
  },
  'return.received': {
    key: 'return.received',
    name: 'Return Received',
    category: 'returns',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Return received for order {{orderNumber}}',
    bodyTemplate: 'The seller has confirmed receipt of your return for order {{orderNumber}}. Your refund will be processed shortly.',
  },
  'return.auto_approved': {
    key: 'return.auto_approved',
    name: 'Return Auto-Approved',
    category: 'returns',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your return request has been automatically approved',
    bodyTemplate: 'Your return request for order {{orderNumber}} has been automatically approved because the seller did not respond within 3 business days.',
  },
  'dispute.opened': {
    key: 'dispute.opened',
    name: 'Dispute Opened',
    category: 'disputes',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Dispute opened for order {{orderNumber}}',
    bodyTemplate: 'A dispute has been opened for order {{orderNumber}}. Twicely will review the case and make a decision within 48 hours.',
  },
  'dispute.resolved': {
    key: 'dispute.resolved',
    name: 'Dispute Resolved',
    category: 'disputes',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Dispute resolved for order {{orderNumber}}',
    bodyTemplate: 'The dispute for order {{orderNumber}} has been resolved. Resolution: {{resolution}}.',
  },
  'protection.claim_submitted': {
    key: 'protection.claim_submitted',
    name: 'Protection Claim Submitted',
    category: 'protection',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your buyer protection claim has been received',
    bodyTemplate: 'We received your buyer protection claim for order {{orderNumber}}. We will review your case and respond within 48 hours.',
  },
  'shipping.exception': {
    key: 'shipping.exception',
    name: 'Shipping Exception Detected',
    category: 'shipping',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Shipping issue detected for order {{orderNumber}}',
    bodyTemplate: 'We noticed a potential shipping issue with order {{orderNumber}}: {{exceptionType}}. We have automatically opened a protection claim on your behalf.',
  },
};
