import type { TemplateDef } from '@twicely/notifications/templates';

export const ENFORCEMENT_TEMPLATES: Record<string, TemplateDef> = {
  'enforcement.coaching': {
    key: 'enforcement.coaching',
    name: 'Enforcement: Coaching',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Tips to improve your selling performance',
    bodyTemplate: 'We noticed some areas where your selling activity could be improved. Review our seller standards to keep your account in good standing.',
  },
  'enforcement.warning': {
    key: 'enforcement.warning',
    name: 'Enforcement: Warning',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Action required: Your selling performance needs attention',
    bodyTemplate: 'Your account has received a formal warning due to your recent selling activity. You have {{daysToImprove}} days to bring your performance up to our seller standards.',
  },
  'enforcement.restriction': {
    key: 'enforcement.restriction',
    name: 'Enforcement: Restriction',
    category: 'trust',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your account has been restricted',
    bodyTemplate: 'Your selling account has been restricted due to ongoing performance concerns. Certain selling features are limited. Contact support if you believe this is an error.',
  },
  'enforcement.lifted': {
    key: 'enforcement.lifted',
    name: 'Enforcement: Lifted',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Account restriction has been lifted',
    bodyTemplate: 'The enforcement action on your account has been lifted. Your account is now in good standing. Continue meeting our seller standards to maintain your status.',
  },
  'enforcement.band_upgrade': {
    key: 'enforcement.band_upgrade',
    name: 'Performance Band Upgrade',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Congratulations! You\'ve reached {{bandName}} status',
    bodyTemplate: 'Congratulations! Your selling performance has earned you {{bandName}} status. Keep up the great work to maintain your standing.',
  },
  'enforcement.band_downgrade': {
    key: 'enforcement.band_downgrade',
    name: 'Performance Band Downgrade',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your performance status has changed',
    bodyTemplate: 'Your performance status has changed. Visit your performance dashboard to see your current metrics and tips for improvement.',
  },
  'enforcement.appeal_submitted': {
    key: 'enforcement.appeal_submitted',
    name: 'Appeal Submitted (Staff Notification)',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'New enforcement appeal requires review',
    bodyTemplate: 'A seller has appealed a {{actionType}} enforcement action. Please review within 48 hours.',
  },
  'enforcement.appeal_approved': {
    key: 'enforcement.appeal_approved',
    name: 'Appeal Approved (Seller Notification)',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your appeal has been approved',
    bodyTemplate: 'Your appeal regarding the {{actionType}} enforcement action has been reviewed and approved. The action has been lifted and your account is back in good standing.',
  },
  'enforcement.appeal_denied': {
    key: 'enforcement.appeal_denied',
    name: 'Appeal Denied (Seller Notification)',
    category: 'trust',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your appeal has been reviewed',
    bodyTemplate: 'Your appeal regarding the {{actionType}} enforcement action has been reviewed. After careful consideration, the original enforcement action will remain in effect. Review our seller standards for guidance on improving your account standing.',
  },
};
