/**
 * Tests for messaging.ts queries — getConversations, getConversationMessages
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── Mocks ───────────────────────────────────────────────────────────────────

vi.mock('@twicely/db', () => ({
  db: { select: vi.fn() },
}));

import { db } from '@twicely/db';
import type { Mock } from 'vitest';

const mockSelect = db.select as Mock;

// ─── Chain Helper ─────────────────────────────────────────────────────────────

function makeChain(rows: unknown[]) {
  const chainable: Record<string, unknown> = {};
  const methods = ['from', 'leftJoin', 'innerJoin', 'where', 'orderBy', 'limit'];
  for (const m of methods) {
    chainable[m] = vi.fn().mockImplementation(() => chainable);
  }
  (chainable.orderBy as Mock).mockResolvedValue(rows);
  (chainable.limit as Mock).mockResolvedValue(rows);
  return chainable;
}

// ─── Test Data ────────────────────────────────────────────────────────────────

const BUYER_ID = 'buyer-test-001';
const SELLER_ID = 'seller-test-002';
const CONV_ID = 'conv-test-001';
const LISTING_ID = 'listing-test-001';
const NOW = new Date('2026-01-15T12:00:00Z');

const rawConvRow = {
  id: CONV_ID,
  listingId: LISTING_ID,
  orderId: null,
  buyerId: BUYER_ID,
  sellerId: SELLER_ID,
  subject: 'Cool Jacket',
  status: 'OPEN',
  lastMessageAt: NOW,
  buyerUnreadCount: 2,
  sellerUnreadCount: 0,
  createdAt: NOW,
  listingTitle: 'Cool Jacket',
  listingSlug: 'cool-jacket-abc',
  listingImageUrl: 'https://cdn.example.com/jacket.jpg',
  otherBuyerName: 'Alice Buyer',
  otherBuyerImage: 'https://cdn.example.com/alice.jpg',
  otherSellerName: 'Bob Seller',
  otherSellerImage: 'https://cdn.example.com/bob.jpg',
};

const convDetailRow = {
  id: CONV_ID,
  listingId: LISTING_ID,
  orderId: null,
  buyerId: BUYER_ID,
  sellerId: SELLER_ID,
  subject: 'Cool Jacket',
  status: 'OPEN',
  isFlagged: false,
  createdAt: NOW,
  listingTitle: 'Cool Jacket',
  listingSlug: 'cool-jacket-abc',
  listingPriceCents: 4999,
  listingImageUrl: 'https://cdn.example.com/jacket.jpg',
};

const rawMessageRow = {
  id: 'msg-test-001',
  senderUserId: BUYER_ID,
  senderName: 'Alice Buyer',
  body: 'Is this still available?',
  attachments: [],
  isRead: false,
  readAt: null,
  isAutoGenerated: false,
  createdAt: NOW,
};

const sellerUserRow = {
  name: 'Bob Seller',
  image: 'https://cdn.example.com/bob.jpg',
};

// ─── getConversations ─────────────────────────────────────────────────────────

describe('getConversations', () => {
  beforeEach(() => vi.clearAllMocks());

  it('returns conversations for a buyer with correct other-party mapping', async () => {
    mockSelect.mockReturnValueOnce(makeChain([rawConvRow]) as never);

    const { getConversations } = await import('../messaging');
    const result = await getConversations(BUYER_ID, 'buyer');

    expect(result).toHaveLength(1);
    const conv = result[0];
    expect(conv?.id).toBe(CONV_ID);
    expect(conv?.otherPartyId).toBe(SELLER_ID);
    expect(conv?.otherPartyName).toBe('Bob Seller');
    expect(conv?.unreadCount).toBe(2);
  });

  it('returns conversations for a seller with correct other-party mapping', async () => {
    const sellerRow = { ...rawConvRow, buyerUnreadCount: 0, sellerUnreadCount: 3 };
    mockSelect.mockReturnValueOnce(makeChain([sellerRow]) as never);

    const { getConversations } = await import('../messaging');
    const result = await getConversations(SELLER_ID, 'seller');

    expect(result).toHaveLength(1);
    const conv = result[0];
    expect(conv?.otherPartyId).toBe(BUYER_ID);
    expect(conv?.otherPartyName).toBe('Alice Buyer');
    expect(conv?.unreadCount).toBe(3);
  });

  it('returns empty array for user with no conversations', async () => {
    mockSelect.mockReturnValueOnce(makeChain([]) as never);

    const { getConversations } = await import('../messaging');
    const result = await getConversations('user-no-convs', 'both');

    expect(result).toEqual([]);
  });

  it('falls back to "Unknown" when other party name is null', async () => {
    const rowNullName = { ...rawConvRow, otherSellerName: null, otherSellerImage: null };
    mockSelect.mockReturnValueOnce(makeChain([rowNullName]) as never);

    const { getConversations } = await import('../messaging');
    const result = await getConversations(BUYER_ID, 'buyer');

    expect(result[0]?.otherPartyName).toBe('Unknown');
  });

  it('sets otherPartyImage to null when image is undefined', async () => {
    const rowNoImg = { ...rawConvRow, otherSellerImage: undefined };
    mockSelect.mockReturnValueOnce(makeChain([rowNoImg]) as never);

    const { getConversations } = await import('../messaging');
    const result = await getConversations(BUYER_ID, 'buyer');

    expect(result[0]?.otherPartyImage).toBeNull();
  });

  it('maps listingImageUrl to null when no listing image', async () => {
    const rowNoImg = { ...rawConvRow, listingImageUrl: null };
    mockSelect.mockReturnValueOnce(makeChain([rowNoImg]) as never);

    const { getConversations } = await import('../messaging');
    const result = await getConversations(BUYER_ID, 'buyer');

    expect(result[0]?.listingImageUrl).toBeNull();
  });
});

// ─── getConversationMessages ──────────────────────────────────────────────────

describe('getConversationMessages', () => {
  beforeEach(() => vi.clearAllMocks());

  it('returns conversation detail and messages for buyer participant', async () => {
    mockSelect
      .mockReturnValueOnce(makeChain([convDetailRow]) as never)
      .mockReturnValueOnce(makeChain([sellerUserRow]) as never)
      .mockReturnValueOnce(makeChain([rawMessageRow]) as never);

    const { getConversationMessages } = await import('../messaging');
    const result = await getConversationMessages(CONV_ID, BUYER_ID);

    expect(result).not.toBeNull();
    expect(result?.conversation.id).toBe(CONV_ID);
    expect(result?.conversation.isFlagged).toBe(false);
    expect(result?.messages).toHaveLength(1);
    expect(result?.messages[0]?.body).toBe('Is this still available?');
    expect(result?.messages[0]?.senderName).toBe('Alice Buyer');
  });

  it('returns null when conversation does not exist', async () => {
    mockSelect.mockReturnValueOnce(makeChain([]) as never);

    const { getConversationMessages } = await import('../messaging');
    const result = await getConversationMessages('nonexistent-conv', BUYER_ID);

    expect(result).toBeNull();
  });

  it('returns null for non-participant (not buyer or seller)', async () => {
    mockSelect.mockReturnValueOnce(makeChain([convDetailRow]) as never);

    const { getConversationMessages } = await import('../messaging');
    const result = await getConversationMessages(CONV_ID, 'outsider-user-999');

    expect(result).toBeNull();
  });

  it('returns empty messages array when conversation has no messages', async () => {
    mockSelect
      .mockReturnValueOnce(makeChain([convDetailRow]) as never)
      .mockReturnValueOnce(makeChain([sellerUserRow]) as never)
      .mockReturnValueOnce(makeChain([]) as never);

    const { getConversationMessages } = await import('../messaging');
    const result = await getConversationMessages(CONV_ID, BUYER_ID);

    expect(result?.messages).toEqual([]);
  });

  it('maps listingPriceCents to null when listing has no price', async () => {
    const convNoPrice = { ...convDetailRow, listingPriceCents: null };
    mockSelect
      .mockReturnValueOnce(makeChain([convNoPrice]) as never)
      .mockReturnValueOnce(makeChain([sellerUserRow]) as never)
      .mockReturnValueOnce(makeChain([]) as never);

    const { getConversationMessages } = await import('../messaging');
    const result = await getConversationMessages(CONV_ID, BUYER_ID);

    expect(result?.conversation.listingPriceCents).toBeNull();
  });
});
