/**
 * Logic tests for ConversationThread — optimistic message deduplication logic.
 *
 * Pure-logic extraction: mirrors the exact branches in
 * conversation-thread.tsx without needing a DOM or React.
 */
import { describe, it, expect } from 'vitest';
import type { MessageItem } from '@/lib/queries/messaging';

// ─── Constants from conversation-thread.tsx ──────────────────────────────────

const TEMP_ID_PREFIX = 'temp-';
const DEDUP_WINDOW_MS = 5000;

// ─── Pure logic extracted from handleNewMessage callback ─────────────────────

function applyNewMessage(
  prev: MessageItem[],
  incoming: MessageItem,
  nowMs: number,
): MessageItem[] {
  const matchIndex = prev.findIndex(
    (m) =>
      m.id.startsWith(TEMP_ID_PREFIX) &&
      m.senderUserId === incoming.senderUserId &&
      m.body === incoming.body &&
      nowMs - new Date(m.createdAt).getTime() < DEDUP_WINDOW_MS,
  );
  if (matchIndex !== -1) {
    const updated = [...prev];
    updated[matchIndex] = incoming;
    return updated;
  }
  return [...prev, incoming];
}

// ─── Test data ────────────────────────────────────────────────────────────────

const BUYER_ID = 'user-buyer-dedup-001';
const SELLER_ID = 'user-seller-dedup-002';

function makeMsg(overrides: Partial<MessageItem> = {}): MessageItem {
  return {
    id: 'msg-test-001',
    senderUserId: BUYER_ID,
    senderName: 'Alice',
    body: 'Hello',
    attachments: [],
    isRead: true,
    readAt: new Date(),
    isAutoGenerated: false,
    createdAt: new Date(),
    ...overrides,
  };
}

// ─── Deduplication logic tests ────────────────────────────────────────────────

describe('ConversationThread — optimistic dedup (applyNewMessage)', () => {
  it('appends new message when no matching optimistic message exists', () => {
    const prev = [makeMsg({ id: 'msg-real-001' })];
    const incoming = makeMsg({ id: 'msg-real-002', body: 'New message' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).toHaveLength(2);
    expect(result[1]).toBe(incoming);
  });

  it('replaces matching temp message with real message', () => {
    const tempCreated = Date.now() - 1000;
    const prev = [
      makeMsg({
        id: `${TEMP_ID_PREFIX}${tempCreated}`,
        senderUserId: BUYER_ID,
        body: 'Optimistic!',
        createdAt: new Date(tempCreated),
      }),
    ];
    const incoming = makeMsg({ id: 'msg-real-server-001', senderUserId: BUYER_ID, body: 'Optimistic!' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).toHaveLength(1);
    expect(result[0]!.id).toBe('msg-real-server-001');
    expect(result[0]!.id).not.toContain(TEMP_ID_PREFIX);
  });

  it('does NOT replace when body differs', () => {
    const tempCreated = Date.now() - 1000;
    const prev = [
      makeMsg({
        id: `${TEMP_ID_PREFIX}${tempCreated}`,
        senderUserId: BUYER_ID,
        body: 'First message',
        createdAt: new Date(tempCreated),
      }),
    ];
    const incoming = makeMsg({ id: 'msg-real-002', senderUserId: BUYER_ID, body: 'Different message' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).toHaveLength(2);
    expect(result[0]!.id).toContain(TEMP_ID_PREFIX);
  });

  it('does NOT replace when senderUserId differs', () => {
    const tempCreated = Date.now() - 1000;
    const prev = [
      makeMsg({
        id: `${TEMP_ID_PREFIX}${tempCreated}`,
        senderUserId: BUYER_ID,
        body: 'Same body',
        createdAt: new Date(tempCreated),
      }),
    ];
    const incoming = makeMsg({ id: 'msg-real-003', senderUserId: SELLER_ID, body: 'Same body' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).toHaveLength(2);
  });

  it('does NOT replace stale optimistic message (> DEDUP_WINDOW_MS old)', () => {
    const staleCreated = Date.now() - DEDUP_WINDOW_MS - 1000;
    const prev = [
      makeMsg({
        id: `${TEMP_ID_PREFIX}${staleCreated}`,
        senderUserId: BUYER_ID,
        body: 'Old message',
        createdAt: new Date(staleCreated),
      }),
    ];
    const incoming = makeMsg({ id: 'msg-real-late', senderUserId: BUYER_ID, body: 'Old message' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).toHaveLength(2);
    expect(result[1]!.id).toBe('msg-real-late');
  });

  it('replaces only the FIRST matching temp message when duplicates exist', () => {
    const tempCreated = Date.now() - 500;
    const prev = [
      makeMsg({ id: `${TEMP_ID_PREFIX}111`, senderUserId: BUYER_ID, body: 'Same', createdAt: new Date(tempCreated) }),
      makeMsg({ id: `${TEMP_ID_PREFIX}222`, senderUserId: BUYER_ID, body: 'Same', createdAt: new Date(tempCreated) }),
    ];
    const incoming = makeMsg({ id: 'msg-real-first', senderUserId: BUYER_ID, body: 'Same' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).toHaveLength(2);
    expect(result[0]!.id).toBe('msg-real-first');
    expect(result[1]!.id).toBe(`${TEMP_ID_PREFIX}222`);
  });

  it('returns a new array (does not mutate prev)', () => {
    const prev = [makeMsg({ id: 'msg-orig' })];
    const incoming = makeMsg({ id: 'msg-new' });
    const result = applyNewMessage(prev, incoming, Date.now());

    expect(result).not.toBe(prev);
    expect(prev).toHaveLength(1);
    expect(result).toHaveLength(2);
  });
});
