/**
 * Logic tests for ConversationThread — read receipt logic,
 * lastNonSystemMessageId finding, and TypingIndicator visibility gate.
 *
 * Pure-logic extractions that mirror exact branches in conversation-thread.tsx.
 */
import { describe, it, expect } from 'vitest';
import type { MessageItem } from '@/lib/queries/messaging';

// ─── Constants ────────────────────────────────────────────────────────────────

const TEMP_ID_PREFIX = 'temp-';

// ─── Pure logic ───────────────────────────────────────────────────────────────

function getLastReadOwnMessageId(
  messages: MessageItem[],
  currentUserId: string,
): string | null {
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg && msg.senderUserId === currentUserId && !msg.isAutoGenerated && msg.isRead) {
      return msg.id;
    }
  }
  return null;
}

function getLastNonSystemMessageId(messages: MessageItem[]): string | null {
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg && !msg.isAutoGenerated && !msg.id.startsWith(TEMP_ID_PREFIX)) {
      return msg.id;
    }
  }
  return null;
}

function typingIndicatorVisible(
  typingUserId: string | null,
  status: 'OPEN' | 'READ_ONLY' | 'ARCHIVED',
): boolean {
  return typingUserId !== null && status === 'OPEN';
}

// ─── Test data ────────────────────────────────────────────────────────────────

const BUYER_ID = 'user-buyer-rr-001';
const SELLER_ID = 'user-seller-rr-002';

function makeMsg(overrides: Partial<MessageItem> = {}): MessageItem {
  return {
    id: 'msg-test-001',
    senderUserId: BUYER_ID,
    senderName: 'Alice',
    body: 'Hello',
    attachments: [],
    isRead: true,
    readAt: new Date(),
    isAutoGenerated: false,
    createdAt: new Date(),
    ...overrides,
  };
}

// ─── getLastReadOwnMessageId ──────────────────────────────────────────────────

describe('ConversationThread — getLastReadOwnMessageId', () => {
  it('returns the last read own message id', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-read-1', isRead: true }),
      makeMsg({ id: 'msg-read-2', isRead: true }),
    ];
    expect(getLastReadOwnMessageId(messages, BUYER_ID)).toBe('msg-read-2');
  });

  it('skips unread own messages', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-read-1', isRead: true }),
      makeMsg({ id: 'msg-unread', isRead: false }),
    ];
    expect(getLastReadOwnMessageId(messages, BUYER_ID)).toBe('msg-read-1');
  });

  it('returns null when no own read messages', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-other', senderUserId: SELLER_ID, isRead: true }),
    ];
    expect(getLastReadOwnMessageId(messages, BUYER_ID)).toBeNull();
  });

  it('skips auto-generated messages even if own and read', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-system', isAutoGenerated: true, isRead: true }),
    ];
    expect(getLastReadOwnMessageId(messages, BUYER_ID)).toBeNull();
  });

  it('returns null for empty message list', () => {
    expect(getLastReadOwnMessageId([], BUYER_ID)).toBeNull();
  });

  it('returns last in list when multiple own read messages exist', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-a', isRead: true }),
      makeMsg({ id: 'msg-b', isRead: true }),
      makeMsg({ id: 'msg-c', isRead: true }),
    ];
    expect(getLastReadOwnMessageId(messages, BUYER_ID)).toBe('msg-c');
  });
});

// ─── getLastNonSystemMessageId ────────────────────────────────────────────────

describe('ConversationThread — getLastNonSystemMessageId', () => {
  it('returns the last real (non-system, non-temp) message id', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-real-001' }),
      makeMsg({ id: 'msg-real-002' }),
    ];
    expect(getLastNonSystemMessageId(messages)).toBe('msg-real-002');
  });

  it('skips auto-generated (system) messages', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-real-001' }),
      makeMsg({ id: 'msg-system', isAutoGenerated: true }),
    ];
    expect(getLastNonSystemMessageId(messages)).toBe('msg-real-001');
  });

  it('skips temp-prefixed optimistic messages', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-real-001' }),
      makeMsg({ id: `${TEMP_ID_PREFIX}12345`, body: 'Optimistic' }),
    ];
    expect(getLastNonSystemMessageId(messages)).toBe('msg-real-001');
  });

  it('returns null when only system messages exist', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-sys-1', isAutoGenerated: true }),
    ];
    expect(getLastNonSystemMessageId(messages)).toBeNull();
  });

  it('returns null when only optimistic messages exist', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: `${TEMP_ID_PREFIX}111`, body: 'Pending' }),
    ];
    expect(getLastNonSystemMessageId(messages)).toBeNull();
  });

  it('returns null for empty message list', () => {
    expect(getLastNonSystemMessageId([])).toBeNull();
  });

  it('seller messages (not auto-generated) count as non-system', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-seller-001', senderUserId: SELLER_ID }),
    ];
    expect(getLastNonSystemMessageId(messages)).toBe('msg-seller-001');
  });

  it('report button hidden when lastNonSystemMessageId is null (only system messages)', () => {
    const messages: MessageItem[] = [
      makeMsg({ id: 'msg-system', isAutoGenerated: true }),
    ];
    const lastRealId = getLastNonSystemMessageId(messages);
    // report button requires lastNonSystemMessageId && status === 'OPEN'
    const reportButtonVisible = lastRealId !== null;
    expect(reportButtonVisible).toBe(false);
  });
});

// ─── TypingIndicator visibility gate ─────────────────────────────────────────

describe('ConversationThread — TypingIndicator visibility', () => {
  it('shows typing indicator when userId is set and status is OPEN', () => {
    expect(typingIndicatorVisible(SELLER_ID, 'OPEN')).toBe(true);
  });

  it('hides typing indicator when no userId is set (null)', () => {
    expect(typingIndicatorVisible(null, 'OPEN')).toBe(false);
  });

  it('hides typing indicator when status is READ_ONLY (even with userId set)', () => {
    expect(typingIndicatorVisible(SELLER_ID, 'READ_ONLY')).toBe(false);
  });

  it('hides typing indicator when status is ARCHIVED', () => {
    expect(typingIndicatorVisible(SELLER_ID, 'ARCHIVED')).toBe(false);
  });

  it('hides typing indicator when both userId is null and status is READ_ONLY', () => {
    expect(typingIndicatorVisible(null, 'READ_ONLY')).toBe(false);
  });

  it('typing userId from different user (not self) triggers indicator in OPEN conversation', () => {
    // The hook filters out self-typing; if userId is set here, it's already filtered
    expect(typingIndicatorVisible('other-user-001', 'OPEN')).toBe(true);
  });
});
