/**
 * Extended logic tests for ConversationThread — additional edge cases.
 */
import { describe, it, expect } from 'vitest';
import type { ConversationDetail, MessageItem } from '@/lib/queries/messaging';

// ─── Pure logic extracted from ConversationThread ─────────────────────────────

function getListingHref(slug: string | null): string | null {
  if (!slug) return null;
  return `/i/${slug}`;
}

function shouldShowListingContextCard(slug: string | null): boolean {
  return slug !== null;
}

function shouldShowListingPrice(priceCents: number | null): boolean {
  return priceCents !== null;
}

function shouldShowListingImage(imageUrl: string | null): boolean {
  return imageUrl !== null;
}

function shouldShowOrderLinkedBadge(orderId: string | null): boolean {
  return orderId !== null;
}

function getAvatarInitial(senderName: string): string {
  return senderName.charAt(0).toUpperCase();
}

function isSystemMessage(msg: MessageItem): boolean {
  return msg.isAutoGenerated;
}

function isOwnMessage(senderUserId: string, currentUserId: string): boolean {
  return senderUserId === currentUserId;
}

function shouldShowCompose(status: ConversationDetail['status']): boolean {
  return status === 'OPEN';
}

function getSubjectDisplay(subject: string | null): string {
  return subject ?? 'Conversation';
}

function getFlaggedBannerText(): string {
  return 'For your protection, complete transactions on Twicely.';
}

function getClosedBannerText(): string {
  return 'This conversation is closed.';
}

// ─── Test Data ────────────────────────────────────────────────────────────────

const BUYER_ID = 'user-buyer-001';
const SELLER_ID = 'user-seller-001';

function makeConversation(overrides: Partial<ConversationDetail> = {}): ConversationDetail {
  return {
    id: 'conv-test-001',
    listingId: 'listing-test-001',
    orderId: null,
    buyerId: BUYER_ID,
    sellerId: SELLER_ID,
    subject: 'Vintage Camera',
    status: 'OPEN',
    isFlagged: false,
    createdAt: new Date('2026-01-01'),
    listingTitle: 'Vintage Camera',
    listingSlug: 'vintage-camera-abc',
    listingPriceCents: 4999,
    listingImageUrl: 'https://cdn.example.com/camera.jpg',
    otherPartyId: SELLER_ID,
    otherPartyName: 'Bob Seller',
    otherPartyImage: null,
    ...overrides,
  };
}

function makeMessage(overrides: Partial<MessageItem> = {}): MessageItem {
  return {
    id: 'msg-test-001',
    senderUserId: BUYER_ID,
    senderName: 'Alice Buyer',
    body: 'Is this available?',
    attachments: [],
    isRead: true,
    readAt: new Date(),
    isAutoGenerated: false,
    createdAt: new Date('2026-01-10'),
    ...overrides,
  };
}

// ─── Listing context card ─────────────────────────────────────────────────────

describe('ConversationThread — listing context card', () => {
  it('shows listing card when listingSlug is present', () => {
    const conv = makeConversation({ listingSlug: 'vintage-camera-abc' });
    expect(shouldShowListingContextCard(conv.listingSlug)).toBe(true);
  });

  it('hides listing card when listingSlug is null', () => {
    const conv = makeConversation({ listingSlug: null });
    expect(shouldShowListingContextCard(conv.listingSlug)).toBe(false);
  });

  it('listing link points to /i/:slug route', () => {
    expect(getListingHref('vintage-camera-abc')).toBe('/i/vintage-camera-abc');
  });

  it('listing link returns null when slug is null', () => {
    expect(getListingHref(null)).toBeNull();
  });

  it('shows price when listingPriceCents is not null', () => {
    const conv = makeConversation({ listingPriceCents: 4999 });
    expect(shouldShowListingPrice(conv.listingPriceCents)).toBe(true);
  });

  it('hides price when listingPriceCents is null', () => {
    const conv = makeConversation({ listingPriceCents: null });
    expect(shouldShowListingPrice(conv.listingPriceCents)).toBe(false);
  });

  it('shows listing image when imageUrl is present', () => {
    const conv = makeConversation({ listingImageUrl: 'https://cdn.example.com/img.jpg' });
    expect(shouldShowListingImage(conv.listingImageUrl)).toBe(true);
  });

  it('hides listing image when imageUrl is null', () => {
    const conv = makeConversation({ listingImageUrl: null });
    expect(shouldShowListingImage(conv.listingImageUrl)).toBe(false);
  });
});

// ─── Order badge ──────────────────────────────────────────────────────────────

describe('ConversationThread — order badge', () => {
  it('shows "Order linked" badge when orderId is present', () => {
    const conv = makeConversation({ orderId: 'order-test-001' });
    expect(shouldShowOrderLinkedBadge(conv.orderId)).toBe(true);
  });

  it('hides "Order linked" badge when orderId is null', () => {
    const conv = makeConversation({ orderId: null });
    expect(shouldShowOrderLinkedBadge(conv.orderId)).toBe(false);
  });
});

// ─── Subject display ──────────────────────────────────────────────────────────

describe('ConversationThread — subject display', () => {
  it('shows subject when present', () => {
    expect(getSubjectDisplay('Vintage Camera')).toBe('Vintage Camera');
  });

  it('falls back to "Conversation" when subject is null', () => {
    expect(getSubjectDisplay(null)).toBe('Conversation');
  });
});

// ─── Compose area / closed banner ────────────────────────────────────────────

describe('ConversationThread — compose vs closed banner', () => {
  it('shows MessageComposer when status is OPEN', () => {
    expect(shouldShowCompose('OPEN')).toBe(true);
  });

  it('shows closed banner when status is READ_ONLY', () => {
    expect(shouldShowCompose('READ_ONLY')).toBe(false);
  });

  it('shows closed banner when status is ARCHIVED', () => {
    expect(shouldShowCompose('ARCHIVED')).toBe(false);
  });

  it('closed banner text matches spec', () => {
    expect(getClosedBannerText()).toBe('This conversation is closed.');
  });
});

// ─── Off-platform warning banner ──────────────────────────────────────────────

describe('ConversationThread — off-platform warning banner', () => {
  it('shows warning banner when isFlagged is true', () => {
    const conv = makeConversation({ isFlagged: true });
    expect(conv.isFlagged).toBe(true);
  });

  it('hides warning banner when isFlagged is false', () => {
    const conv = makeConversation({ isFlagged: false });
    expect(conv.isFlagged).toBe(false);
  });

  it('warning banner text matches safety spec', () => {
    expect(getFlaggedBannerText()).toBe(
      'For your protection, complete transactions on Twicely.',
    );
  });
});

// ─── Message bubble alignment and avatar ────────────────────────────────────

describe('ConversationThread — message bubble alignment', () => {
  it('own message aligns right (senderUserId === currentUserId)', () => {
    expect(isOwnMessage(BUYER_ID, BUYER_ID)).toBe(true);
  });

  it('other party message aligns left (senderUserId !== currentUserId)', () => {
    expect(isOwnMessage(SELLER_ID, BUYER_ID)).toBe(false);
  });

  it('auto-generated message is NOT treated as own message', () => {
    const msg = makeMessage({ senderUserId: 'system', isAutoGenerated: true });
    expect(isSystemMessage(msg)).toBe(true);
  });

  it('normal buyer message is not a system message', () => {
    const msg = makeMessage({ senderUserId: BUYER_ID, isAutoGenerated: false });
    expect(isSystemMessage(msg)).toBe(false);
  });
});

// ─── Avatar initial extraction ────────────────────────────────────────────────

describe('ConversationThread — avatar initial', () => {
  it('extracts first character uppercased for "Alice"', () => {
    expect(getAvatarInitial('Alice Buyer')).toBe('A');
  });

  it('extracts first character uppercased for "bob" (lowercase)', () => {
    expect(getAvatarInitial('bob')).toBe('B');
  });

  it('handles single character name', () => {
    expect(getAvatarInitial('Z')).toBe('Z');
  });

  it('returns uppercase initial for lowercase name', () => {
    expect(getAvatarInitial('john doe')).toBe('J');
  });
});

// ─── Message list edge cases ──────────────────────────────────────────────────

describe('ConversationThread — message list edge cases', () => {
  it('handles empty messages array gracefully', () => {
    const messages: MessageItem[] = [];
    expect(messages.length).toBe(0);
  });

  it('handles conversation with only auto-generated messages', () => {
    const messages = [
      makeMessage({ isAutoGenerated: true, senderUserId: 'system', senderName: 'System' }),
    ];
    expect(messages.every((m) => m.isAutoGenerated)).toBe(true);
  });

  it('handles mix of own, other, and system messages', () => {
    const messages = [
      makeMessage({ senderUserId: BUYER_ID, isAutoGenerated: false }),
      makeMessage({ senderUserId: SELLER_ID, isAutoGenerated: false }),
      makeMessage({ senderUserId: 'system', isAutoGenerated: true }),
    ];
    const ownCount = messages.filter((m) => isOwnMessage(m.senderUserId, BUYER_ID)).length;
    const otherCount = messages.filter(
      (m) => !isOwnMessage(m.senderUserId, BUYER_ID) && !m.isAutoGenerated,
    ).length;
    const systemCount = messages.filter((m) => m.isAutoGenerated).length;
    expect(ownCount).toBe(1);
    expect(otherCount).toBe(1);
    expect(systemCount).toBe(1);
  });
});
