import { describe, it, expect } from 'vitest';
import type { ConversationDetail, MessageItem } from '@/lib/queries/messaging';

// Logic tests for ConversationThread rendering decisions

function getMessageAlignment(senderUserId: string, currentUserId: string): 'right' | 'left' {
  return senderUserId === currentUserId ? 'right' : 'left';
}

function shouldShowCompose(status: ConversationDetail['status']): boolean {
  return status === 'OPEN';
}

function shouldShowClosedBanner(status: ConversationDetail['status']): boolean {
  return status !== 'OPEN';
}

function shouldShowOffPlatformBanner(isFlagged: boolean): boolean {
  return isFlagged;
}

function getOffPlatformBannerText(): string {
  return 'For your protection, complete transactions on Twicely.';
}

function isAutoGeneratedStyle(msg: MessageItem): { centered: boolean; italic: boolean } {
  return {
    centered: msg.isAutoGenerated,
    italic: msg.isAutoGenerated,
  };
}

function getListingLink(slug: string): string {
  return `/i/${slug}`;
}

function getHeaderName(conv: ConversationDetail): string {
  return conv.otherPartyName;
}

function getOtherPartyInitials(name: string): string {
  return name.split(' ').map((n) => n[0]).join('').toUpperCase().slice(0, 2);
}

function getLastReadOwnMessageId(messages: MessageItem[], currentUserId: string): string | null {
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg && msg.senderUserId === currentUserId && !msg.isAutoGenerated && msg.isRead) {
      return msg.id;
    }
  }
  return null;
}

function shouldShowArchiveButton(status: ConversationDetail['status']): boolean {
  return status !== 'ARCHIVED';
}

function shouldShowReportButton(status: ConversationDetail['status']): boolean {
  return status === 'OPEN';
}

const currentUserId = 'user-buyer-1';
const sellerId = 'user-seller-1';

const baseConversation: ConversationDetail = {
  id: 'conv1',
  listingId: 'listing1',
  orderId: null,
  buyerId: currentUserId,
  sellerId,
  subject: 'Vintage Camera Question',
  status: 'OPEN',
  isFlagged: false,
  createdAt: new Date('2024-01-01'),
  listingTitle: 'Vintage Camera',
  listingSlug: 'vintage-camera-abc',
  listingPriceCents: 4999,
  listingImageUrl: 'https://placehold.co/56x56',
  otherPartyId: sellerId,
  otherPartyName: 'Seller User',
  otherPartyImage: null,
};

const ownMessage: MessageItem = {
  id: 'msg1',
  senderUserId: currentUserId,
  senderName: 'Buyer User',
  body: 'Is this still available?',
  attachments: [],
  isRead: true,
  readAt: new Date(),
  isAutoGenerated: false,
  createdAt: new Date('2024-01-10'),
};

const otherMessage: MessageItem = {
  id: 'msg2',
  senderUserId: sellerId,
  senderName: 'Seller User',
  body: 'Yes it is!',
  attachments: [],
  isRead: false,
  readAt: null,
  isAutoGenerated: false,
  createdAt: new Date('2024-01-11'),
};

const autoMessage: MessageItem = {
  id: 'msg3',
  senderUserId: 'system',
  senderName: 'System',
  body: 'Conversation started',
  attachments: [],
  isRead: true,
  readAt: new Date(),
  isAutoGenerated: true,
  createdAt: new Date('2024-01-09'),
};

describe('ConversationThread rendering logic', () => {
  it('renders message bubbles for all messages', () => {
    const messages = [ownMessage, otherMessage, autoMessage];
    expect(messages.length).toBe(3);
    expect(messages.every((m) => m.id)).toBe(true);
  });

  it('own messages are right-aligned', () => {
    const alignment = getMessageAlignment(currentUserId, currentUserId);
    expect(alignment).toBe('right');
  });

  it('other party messages are left-aligned', () => {
    const alignment = getMessageAlignment(sellerId, currentUserId);
    expect(alignment).toBe('left');
  });

  it('auto-generated messages rendered with distinct styling', () => {
    const style = isAutoGeneratedStyle(autoMessage);
    expect(style.centered).toBe(true);
    expect(style.italic).toBe(true);

    const normalStyle = isAutoGeneratedStyle(ownMessage);
    expect(normalStyle.centered).toBe(false);
  });

  it('listing context card shows title', () => {
    expect(baseConversation.listingTitle).toBe('Vintage Camera');
    expect(baseConversation.listingPriceCents).toBe(4999);
    expect(getListingLink(baseConversation.listingSlug!)).toBe('/i/vintage-camera-abc');
  });

  it('compose area shown when status is OPEN', () => {
    expect(shouldShowCompose('OPEN')).toBe(true);
    expect(shouldShowCompose('READ_ONLY')).toBe(false);
    expect(shouldShowCompose('ARCHIVED')).toBe(false);
  });

  it('compose area hidden when status is READ_ONLY', () => {
    expect(shouldShowCompose('READ_ONLY')).toBe(false);
  });

  it('off-platform warning banner shown when isFlagged is true', () => {
    expect(shouldShowOffPlatformBanner(true)).toBe(true);
    expect(shouldShowOffPlatformBanner(false)).toBe(false);
  });

  it('off-platform warning banner hidden when isFlagged is false', () => {
    expect(shouldShowOffPlatformBanner(false)).toBe(false);
  });

  it('"This conversation is closed" banner shown for non-OPEN status', () => {
    expect(shouldShowClosedBanner('READ_ONLY')).toBe(true);
    expect(shouldShowClosedBanner('ARCHIVED')).toBe(true);
    expect(shouldShowClosedBanner('OPEN')).toBe(false);
  });

  it('off-platform banner has correct text', () => {
    const text = getOffPlatformBannerText();
    expect(text).toBe('For your protection, complete transactions on Twicely.');
  });

  it('header shows otherPartyName', () => {
    expect(getHeaderName(baseConversation)).toBe('Seller User');
  });

  it('avatar fallback shows initials when no image', () => {
    expect(getOtherPartyInitials('Bob Seller')).toBe('BS');
    expect(getOtherPartyInitials('Alice')).toBe('A');
  });

  it('"Read" shown only on last read own message', () => {
    const messages: MessageItem[] = [ownMessage, { ...ownMessage, id: 'msg4', isRead: false }];
    const lastReadId = getLastReadOwnMessageId(messages, currentUserId);
    expect(lastReadId).toBe(ownMessage.id);
  });

  it('"Read" not shown on other party messages', () => {
    const messages: MessageItem[] = [otherMessage];
    const lastReadId = getLastReadOwnMessageId(messages, currentUserId);
    expect(lastReadId).toBeNull();
  });

  it('"Read" not shown on system/auto-generated messages', () => {
    const messages: MessageItem[] = [autoMessage];
    const lastReadId = getLastReadOwnMessageId(messages, currentUserId);
    expect(lastReadId).toBeNull();
  });

  it('archive button hidden when status is ARCHIVED', () => {
    expect(shouldShowArchiveButton('ARCHIVED')).toBe(false);
  });

  it('archive button present when OPEN', () => {
    expect(shouldShowArchiveButton('OPEN')).toBe(true);
  });

  it('archive button present when READ_ONLY', () => {
    expect(shouldShowArchiveButton('READ_ONLY')).toBe(true);
  });

  it('report button present only when OPEN', () => {
    expect(shouldShowReportButton('OPEN')).toBe(true);
    expect(shouldShowReportButton('READ_ONLY')).toBe(false);
    expect(shouldShowReportButton('ARCHIVED')).toBe(false);
  });
});
