import type { PermissionModule } from './permission-registry';

export const PERMISSION_MODULES: PermissionModule[] = [
  {
    subject: 'User',
    name: 'Users',
    description: 'Marketplace user accounts — view, edit, warn, and restrict users',
    category: 'USERS_AND_STAFF',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
      { action: 'impersonate', label: 'Impersonate' },
      { action: 'warn', label: 'Warn' },
      { action: 'restrict', label: 'Restrict' },
      { action: 'message', label: 'Message' },
    ],
  },
  {
    subject: 'CustomRole',
    name: 'Roles',
    description: 'Custom staff roles — create and manage permission sets',
    category: 'USERS_AND_STAFF',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'StaffUser',
    name: 'Staff',
    description: 'Hub staff accounts — manage staff users and their roles',
    category: 'USERS_AND_STAFF',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },

  {
    subject: 'Listing',
    name: 'Listings',
    description: 'Marketplace listings — view, edit, and moderate item listings',
    category: 'COMMERCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
      { action: 'moderate', label: 'Moderate' },
    ],
  },
  {
    subject: 'Category',
    name: 'Categories',
    description: 'Product categories and catalog structure',
    category: 'COMMERCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Order',
    name: 'Orders',
    description: 'Marketplace orders — view and manage order lifecycle',
    category: 'COMMERCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'SellerProfile',
    name: 'Sellers',
    description: 'Seller profiles — view, update, and apply trust actions',
    category: 'COMMERCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Subscription',
    name: 'Subscriptions',
    description: 'Seller subscription management — view and update subscription state',
    category: 'COMMERCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'update', label: 'Edit' },
    ],
  },
  {
    subject: 'Promotion',
    name: 'Promotions',
    description: 'Promotional campaigns and discounts',
    category: 'COMMERCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },

  {
    subject: 'LedgerEntry',
    name: 'Ledger',
    description: 'Financial ledger — view entries and reconciliation (read-only by policy)',
    category: 'FINANCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Payout',
    name: 'Payouts',
    description: 'Seller payouts — view, manage holds, and execute payout transfers',
    category: 'FINANCE',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
      { action: 'execute', label: 'Execute' },
    ],
  },
  {
    subject: 'Analytics',
    name: 'Analytics',
    description: 'Platform analytics and financial dashboards',
    category: 'FINANCE',
    actions: [{ action: 'read', label: 'View' }],
  },
  {
    subject: 'TaxInfo',
    name: 'Tax Info',
    description: 'Seller tax information (SSN/EIN/ITIN) — FINANCE and ADMIN read-only (masked)',
    category: 'FINANCE',
    actions: [
      { action: 'read', label: 'View (masked)' },
      { action: 'update', label: 'Edit' },
    ],
  },
  {
    subject: 'Dispute',
    name: 'Disputes',
    description: 'Buyer protection disputes and chargeback management',
    category: 'TRUST_AND_SAFETY',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Return',
    name: 'Returns',
    description: 'Return requests and return approval workflow',
    category: 'TRUST_AND_SAFETY',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Review',
    name: 'Reviews',
    description: 'Buyer and seller reviews — view, moderate, and manage',
    category: 'TRUST_AND_SAFETY',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
      { action: 'moderate', label: 'Moderate' },
    ],
  },
  {
    subject: 'AuthenticationRequest',
    name: 'Authentication',
    description: 'Item authentication requests for pre-listing verification',
    category: 'TRUST_AND_SAFETY',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },

  {
    subject: 'Message',
    name: 'Messages',
    description: 'Buyer-seller messages — view and manage communications',
    category: 'CONTENT',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Conversation',
    name: 'Conversations',
    description: 'Buyer-seller conversation threads',
    category: 'CONTENT',
    actions: [{ action: 'read', label: 'View' }, { action: 'create', label: 'Create' }, { action: 'update', label: 'Archive' }],
  },
  {
    subject: 'Notification',
    name: 'Notifications',
    description: 'Platform notifications — view and manage notification delivery',
    category: 'CONTENT',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'HelpdeskCase',
    name: 'Helpdesk',
    description: 'Support cases — view, manage, and escalate helpdesk tickets',
    category: 'CONTENT',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Policy',
    name: 'Policies',
    description: 'Platform policy pages — view and publish policy content',
    category: 'CONTENT',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'Setting',
    name: 'Platform Settings',
    description: 'Platform configuration keys — view and update platform settings',
    category: 'PLATFORM',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'update', label: 'Edit' },
    ],
  },
  {
    subject: 'FeatureFlag',
    name: 'Feature Flags',
    description: 'Feature flags — manage feature rollouts and targeting rules',
    category: 'PLATFORM',
    actions: [
      { action: 'read', label: 'View' },
      { action: 'create', label: 'Create' },
      { action: 'update', label: 'Edit' },
      { action: 'delete', label: 'Delete' },
    ],
  },
  {
    subject: 'AuditEvent',
    name: 'Audit Log',
    description: 'Platform audit log — read-only access to security events',
    category: 'PLATFORM',
    actions: [{ action: 'read', label: 'View' }],
  },
  {
    subject: 'HealthCheck',
    name: 'System Health',
    description: 'System health monitoring — view platform health status',
    category: 'PLATFORM',
    actions: [{ action: 'read', label: 'View' }],
  },
];
