import { drizzle } from 'drizzle-orm/postgres-js';
import { notificationTemplate } from '../schema';

const TEMPLATES = [
  {
    id: 'seed-tpl-offer-declined',
    key: 'offer.declined',
    name: 'Offer Declined',
    description: 'Sent to buyer when seller declines their offer',
    category: 'offers',
    subjectTemplate: 'Your offer on {{itemTitle}} was not accepted',
    bodyTemplate: 'Your offer of {{offerAmountFormatted}} on {{itemTitle}} was not accepted. Your payment hold has been released.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-offer-accepted',
    key: 'offer.accepted',
    name: 'Offer Accepted',
    description: 'Sent to buyer when seller accepts their offer',
    category: 'offers',
    subjectTemplate: 'Your offer on {{itemTitle}} was accepted!',
    bodyTemplate: 'Great news! Your offer of {{offerAmountFormatted}} on {{itemTitle}} has been accepted.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-offer-received',
    key: 'offer.received',
    name: 'Offer Received',
    description: 'Sent to seller when a buyer makes an offer',
    category: 'offers',
    subjectTemplate: 'New offer on {{itemTitle}}: {{offerAmountFormatted}}',
    bodyTemplate: 'You have a new offer of {{offerAmountFormatted}} on {{itemTitle}}. Review and respond before it expires.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-offer-countered',
    key: 'offer.countered',
    name: 'Offer Countered',
    description: 'Sent when the other party counters an offer',
    category: 'offers',
    subjectTemplate: 'Counter offer on {{itemTitle}}: {{counterAmountFormatted}}',
    bodyTemplate: 'You received a counter offer of {{counterAmountFormatted}} on {{itemTitle}}.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-offer-expired',
    key: 'offer.expired',
    name: 'Offer Expired',
    description: 'Sent to buyer when their offer expires without response',
    category: 'offers',
    subjectTemplate: 'Your offer on {{itemTitle}} has expired',
    bodyTemplate: 'Your offer of {{offerAmountFormatted}} on {{itemTitle}} has expired. Your payment hold has been released.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-order-confirmed',
    key: 'order.confirmed',
    name: 'Order Confirmed',
    description: 'Sent to buyer when order is confirmed',
    category: 'orders',
    subjectTemplate: 'Order confirmed: {{orderNumber}}',
    bodyTemplate: 'Your order {{orderNumber}} has been confirmed. Total: {{totalFormatted}}',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-order-shipped',
    key: 'order.shipped',
    name: 'Order Shipped',
    description: 'Sent to buyer when seller marks order as shipped',
    category: 'orders',
    subjectTemplate: 'Your order {{orderNumber}} has shipped!',
    bodyTemplate: 'Your order {{orderNumber}} is on its way.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-watchlist-price-drop',
    key: 'watchlist.price_drop',
    name: 'Price Drop Alert',
    description: 'Sent to watchers when a listing price drops',
    category: 'watchlist',
    subjectTemplate: 'Price drop on {{itemTitle}}!',
    bodyTemplate: '{{itemTitle}} dropped from {{oldPriceFormatted}} to {{newPriceFormatted}}.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-watchlist-watcher-offer',
    key: 'watchlist.watcher_offer',
    name: 'Special Offer for Watchers',
    description: 'Sent to watchers when seller broadcasts a special price',
    category: 'watchlist',
    subjectTemplate: 'Special price on {{itemTitle}} you\'re watching!',
    bodyTemplate: 'The seller is offering you a special price of {{discountedPriceFormatted}} (was {{originalPriceFormatted}}) on {{itemTitle}}. This offer expires soon!',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-search-new-match',
    key: 'search.new_match',
    name: 'New Listing Match',
    description: 'Sent when a new listing matches a saved category alert',
    category: 'search',
    subjectTemplate: 'New listing in {{categoryName}}!',
    bodyTemplate: 'A new item matching your alert was just listed: {{itemTitle}}.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-trial-ending',
    key: 'subscription.trial_ending',
    name: 'Trial Ending Soon',
    description: 'Sent 3 days before trial ends to remind user to add payment method',
    category: 'subscription',
    subjectTemplate: 'Your {{productName}} trial ends in {{daysRemaining}} days',
    bodyTemplate: 'Your free trial of {{productName}} ends on {{trialEndDate}}. Add a payment method to continue enjoying all features.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-trial-expired',
    key: 'subscription.trial_expired',
    name: 'Trial Expired',
    description: 'Sent when trial ends and user is downgraded to free tier',
    category: 'subscription',
    subjectTemplate: 'Your {{productName}} trial has ended',
    bodyTemplate: 'Your free trial of {{productName}} has ended. Upgrade now to continue accessing premium features.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-return-requested',
    key: 'return.requested',
    name: 'Return Requested',
    description: 'Sent to seller when buyer requests a return',
    category: 'returns',
    subjectTemplate: 'Return requested for order {{orderNumber}}',
    bodyTemplate: 'A buyer has requested to return an item from order {{orderNumber}}. Reason: {{reason}}. Please respond within 3 business days.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-return-approved',
    key: 'return.approved',
    name: 'Return Approved',
    description: 'Sent to buyer when seller approves their return request',
    category: 'returns',
    subjectTemplate: 'Your return request has been approved',
    bodyTemplate: 'Your return request for order {{orderNumber}} has been approved. Please ship the item back within 7 days.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-return-declined',
    key: 'return.declined',
    name: 'Return Declined',
    description: 'Sent to buyer when seller declines their return request',
    category: 'returns',
    subjectTemplate: 'Your return request was not approved',
    bodyTemplate: 'Your return request for order {{orderNumber}} was not approved. Reason: {{declineReason}}. If you disagree, you can escalate to Twicely support.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-dispute-opened',
    key: 'dispute.opened',
    name: 'Dispute Opened',
    description: 'Sent to both parties when a dispute is escalated',
    category: 'disputes',
    subjectTemplate: 'Dispute opened for order {{orderNumber}}',
    bodyTemplate: 'A dispute has been opened for order {{orderNumber}}. Twicely will review the case and make a decision within 48 hours.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-dispute-resolved',
    key: 'dispute.resolved',
    name: 'Dispute Resolved',
    description: 'Sent to both parties when dispute is resolved',
    category: 'disputes',
    subjectTemplate: 'Dispute resolved for order {{orderNumber}}',
    bodyTemplate: 'The dispute for order {{orderNumber}} has been resolved. Resolution: {{resolution}}.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-protection-claim',
    key: 'protection.claim_submitted',
    name: 'Protection Claim Submitted',
    description: 'Sent to buyer when their protection claim is received',
    category: 'protection',
    subjectTemplate: 'Your buyer protection claim has been received',
    bodyTemplate: 'We received your buyer protection claim for order {{orderNumber}}. We will review your case and respond within 48 hours.',
    channels: ['EMAIL', 'IN_APP'],
  },
  {
    id: 'seed-tpl-shipping-exception',
    key: 'shipping.exception',
    name: 'Shipping Exception Detected',
    description: 'Sent to buyer when shipping exception is auto-detected',
    category: 'shipping',
    subjectTemplate: 'Shipping issue detected for order {{orderNumber}}',
    bodyTemplate: 'We noticed a potential shipping issue with order {{orderNumber}}: {{exceptionType}}. We have automatically opened a protection claim on your behalf.',
    channels: ['EMAIL', 'IN_APP'],
  },
];

export async function seedNotifications(db: ReturnType<typeof drizzle>): Promise<void> {
  await db.insert(notificationTemplate).values(TEMPLATES).onConflictDoNothing();
}
