'use server';

import { revalidatePath } from 'next/cache';
import { authorize } from '@twicely/casl/authorize';
import { db } from '@twicely/db';
import {
  conversation,
  message as messageTable,
  listing,
} from '@twicely/db/schema';
import { eq, and } from 'drizzle-orm';
import { isBuyerBlocked } from '@/lib/queries/buyer-block';
import { checkMessageSafety } from '@/lib/services/message-safety';
import { notifyNewMessage } from '@twicely/notifications/message-notifier';
import {
  getRateLimitPerHour,
  getMessageCountLastHour,
  isParticipant,
  fetchConversation,
} from './messaging-helpers';
import { sendVacationAutoReply } from './vacation-auto-reply';
import {
  createConversationSchema,
  sendMessageSchema,
  type CreateConversationInput,
  type SendMessageInput,
} from '@/lib/validations/messaging';

interface ActionResult {
  success: boolean;
  error?: string;
  conversationId?: string;
  messageId?: string;
}

/**
 * Start a new conversation with a seller about a listing.
 * Decision #38: one conversation per buyer-seller-listing.
 */
export async function createConversation(
  input: CreateConversationInput,
): Promise<ActionResult> {
  const { session, ability } = await authorize();
  if (!session) {
    return { success: false, error: 'Please sign in to send messages' };
  }

  if (!ability.can('create', 'Conversation')) {
    return { success: false, error: 'You do not have permission to create conversations' };
  }

  const parsed = createConversationSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message ?? 'Invalid input' };
  }

  const { listingId, body } = parsed.data;

  const [listingRow] = await db
    .select({
      id: listing.id,
      status: listing.status,
      ownerUserId: listing.ownerUserId,
      title: listing.title,
    })
    .from(listing)
    .where(eq(listing.id, listingId))
    .limit(1);

  if (!listingRow) return { success: false, error: 'Listing not found' };
  if (listingRow.status !== 'ACTIVE') return { success: false, error: 'This listing is not available' };

  if (listingRow.ownerUserId === session.userId) {
    return { success: false, error: 'You cannot message yourself.' };
  }

  const blocked = await isBuyerBlocked(listingRow.ownerUserId, session.userId);
  if (blocked) return { success: false, error: 'Unable to send message.' };

  // Rate limit from platform_settings — applies to all message sending
  const [msgCount, rateLimit] = await Promise.all([
    getMessageCountLastHour(session.userId),
    getRateLimitPerHour(),
  ]);
  if (msgCount >= rateLimit) {
    return { success: false, error: 'You are sending messages too quickly. Please try again later.' };
  }

  // Decision #38: one conversation per buyer-seller-listing
  const [existing] = await db
    .select({ id: conversation.id, status: conversation.status })
    .from(conversation)
    .where(
      and(
        eq(conversation.buyerId, session.userId),
        eq(conversation.sellerId, listingRow.ownerUserId),
        eq(conversation.listingId, listingId),
      ),
    )
    .limit(1);

  if (existing) {
    if (existing.status === 'OPEN') return { success: true, conversationId: existing.id };
    return { success: false, error: 'This conversation is no longer active.' };
  }

  // Off-platform detection on first message — flags but does NOT block
  const safety = checkMessageSafety(body);

  const [newConv] = await db
    .insert(conversation)
    .values({
      listingId,
      buyerId: session.userId,
      sellerId: listingRow.ownerUserId,
      subject: listingRow.title ?? null,
      status: 'OPEN',
      lastMessageAt: new Date(),
      buyerUnreadCount: 0,
      sellerUnreadCount: 1,
      isFlagged: safety.isFlagged,
      flagReason: safety.isFlagged ? safety.flagReason : null,
    })
    .returning({ id: conversation.id });

  if (!newConv) return { success: false, error: 'Failed to create conversation' };

  const [newMsg] = await db
    .insert(messageTable)
    .values({
      conversationId: newConv.id,
      senderUserId: session.userId,
      body,
      attachments: [],
      isAutoGenerated: false,
    })
    .returning({ id: messageTable.id });

  if (!newMsg) return { success: false, error: 'Failed to send message' };

  // Vacation auto-reply — fires at most once per conversation per vacation period
  sendVacationAutoReply(newConv.id, listingRow.ownerUserId, session.userId, session.userId, session.onBehalfOfSellerId).catch(() => {});

  notifyNewMessage(newMsg.id).catch(() => {});
  revalidatePath('/my/messages');

  return { success: true, conversationId: newConv.id };
}

/**
 * Send a message in an existing conversation.
 */
export async function sendMessage(input: SendMessageInput): Promise<ActionResult> {
  const { session, ability } = await authorize();
  if (!session) {
    return { success: false, error: 'Please sign in to send messages' };
  }

  if (!ability.can('create', 'Message')) {
    return { success: false, error: 'You do not have permission to send messages' };
  }

  const parsed = sendMessageSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message ?? 'Invalid input' };
  }

  const { conversationId, body, attachments } = parsed.data;

  const conv = await fetchConversation(conversationId);
  if (!conv) return { success: false, error: 'Not found.' };

  if (!isParticipant(conv, session.userId, session.onBehalfOfSellerId)) {
    return { success: false, error: 'Not found.' };
  }

  if (conv.status !== 'OPEN') {
    return { success: false, error: 'This conversation is closed.' };
  }

  // Block check — bidirectional
  const [blockedBySeller, blockedByBuyer] = await Promise.all([
    isBuyerBlocked(conv.sellerId, conv.buyerId),
    isBuyerBlocked(conv.buyerId, conv.sellerId),
  ]);
  if (blockedBySeller || blockedByBuyer) {
    return { success: false, error: 'Unable to send message.' };
  }

  // Rate limit from platform_settings
  const [msgCount, rateLimit] = await Promise.all([
    getMessageCountLastHour(session.userId),
    getRateLimitPerHour(),
  ]);
  if (msgCount >= rateLimit) {
    return { success: false, error: 'You are sending messages too quickly. Please try again later.' };
  }

  // Off-platform detection — flags but does NOT block
  const safety = checkMessageSafety(body);
  if (safety.isFlagged) {
    await db
      .update(conversation)
      .set({ isFlagged: true, flagReason: safety.flagReason, updatedAt: new Date() })
      .where(eq(conversation.id, conversationId));
  }

  const [newMsg] = await db
    .insert(messageTable)
    .values({
      conversationId,
      senderUserId: session.userId,
      body,
      attachments,
      isAutoGenerated: false,
    })
    .returning({ id: messageTable.id });

  if (!newMsg) return { success: false, error: 'Failed to send message' };

  // Vacation auto-reply — fires at most once per conversation per vacation period
  sendVacationAutoReply(conversationId, conv.sellerId, conv.buyerId, session.userId, session.onBehalfOfSellerId).catch(() => {});

  const isSellerSender =
    conv.sellerId === session.userId ||
    (session.onBehalfOfSellerId !== null && conv.sellerId === session.onBehalfOfSellerId);

  await db
    .update(conversation)
    .set({
      lastMessageAt: new Date(),
      updatedAt: new Date(),
      buyerUnreadCount: isSellerSender ? conv.buyerUnreadCount + 1 : conv.buyerUnreadCount,
      sellerUnreadCount: isSellerSender ? conv.sellerUnreadCount : conv.sellerUnreadCount + 1,
    })
    .where(eq(conversation.id, conversationId));

  notifyNewMessage(newMsg.id).catch(() => {});
  revalidatePath('/my/messages');

  return { success: true, messageId: newMsg.id };
}
