/**
 * Vacation auto-reply helper for messaging actions.
 * Inserts an auto-reply from the seller when a buyer sends a message during vacation.
 * Fires at most once per conversation per vacation period.
 */

import { db } from '@twicely/db';
import { message as messageTable, sellerProfile, conversation } from '@twicely/db/schema';
import { eq, and, gte, sql } from 'drizzle-orm';

interface AutoReplyResult {
  sent: boolean;
}

function buildDefaultReplyBody(vacationEndAt: Date | null): string {
  if (vacationEndAt) {
    const returnDate = vacationEndAt.toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    });
    return `Thanks for your message! I'm currently away until ${returnDate}. I'll respond when I return.`;
  }
  return "Thanks for your message! I'm currently away. I'll respond when I return.";
}

/**
 * Attempt to send a vacation auto-reply.
 * Only fires once per conversation per vacation period (since vacationStartAt).
 */
export async function sendVacationAutoReply(
  conversationId: string,
  sellerUserId: string,
  _buyerUserId: string,
  senderUserId: string,
  onBehalfOfSellerId?: string | null,
): Promise<AutoReplyResult> {
  // Only fire when the buyer sends — not when seller or delegated staff sends
  if (senderUserId === sellerUserId) return { sent: false };
  if (onBehalfOfSellerId && onBehalfOfSellerId === sellerUserId) return { sent: false };

  // Check seller vacation status
  const [sp] = await db
    .select({
      vacationMode: sellerProfile.vacationMode,
      vacationAutoReplyMessage: sellerProfile.vacationAutoReplyMessage,
      vacationStartAt: sellerProfile.vacationStartAt,
      vacationEndAt: sellerProfile.vacationEndAt,
    })
    .from(sellerProfile)
    .where(eq(sellerProfile.userId, sellerUserId))
    .limit(1);

  if (!sp?.vacationMode) return { sent: false };

  // Check if auto-reply already sent in this vacation period
  const since = sp.vacationStartAt ?? new Date(0);
  const [existingAutoReply] = await db
    .select({ id: messageTable.id })
    .from(messageTable)
    .where(
      and(
        eq(messageTable.conversationId, conversationId),
        eq(messageTable.senderUserId, sellerUserId),
        eq(messageTable.isAutoGenerated, true),
        gte(messageTable.createdAt, since),
      ),
    )
    .limit(1);

  if (existingAutoReply) return { sent: false };

  // Build reply body
  const body =
    sp.vacationAutoReplyMessage?.trim() ||
    buildDefaultReplyBody(sp.vacationEndAt);

  // Insert auto-reply message
  await db.insert(messageTable).values({
    conversationId,
    senderUserId: sellerUserId,
    body,
    attachments: [],
    isAutoGenerated: true,
  });

  // Update conversation — increment buyer unread count
  await db
    .update(conversation)
    .set({
      lastMessageAt: new Date(),
      buyerUnreadCount: sql`buyer_unread_count + 1`,
      updatedAt: new Date(),
    })
    .where(eq(conversation.id, conversationId));

  return { sent: true };
}
