import { db } from '@twicely/db';
import { conversation, listing, listingImage } from '@twicely/db/schema';
import { and, desc, eq, not, sql } from 'drizzle-orm';

export interface ConversationSummary {
  id: string;
  listingId: string | null;
  orderId: string | null;
  otherPartyId: string;
  otherPartyName: string;
  otherPartyImage: string | null;
  listingTitle: string | null;
  listingSlug: string | null;
  listingImageUrl: string | null;
  subject: string | null;
  status: 'OPEN' | 'READ_ONLY' | 'ARCHIVED';
  lastMessageAt: Date | null;
  unreadCount: number;
  createdAt: Date;
  lastMessagePreview: string | null;
  lastMessageSenderIsMe: boolean;
}

export interface ConversationDetail {
  id: string;
  listingId: string | null;
  orderId: string | null;
  buyerId: string;
  sellerId: string;
  subject: string | null;
  status: 'OPEN' | 'READ_ONLY' | 'ARCHIVED';
  isFlagged: boolean;
  createdAt: Date;
  listingTitle: string | null;
  listingSlug: string | null;
  listingPriceCents: number | null;
  listingImageUrl: string | null;
  otherPartyId: string;
  otherPartyName: string;
  otherPartyImage: string | null;
}

export interface MessageItem {
  id: string;
  senderUserId: string;
  senderName: string;
  body: string;
  attachments: string[];
  isRead: boolean;
  readAt: Date | null;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export async function getConversations(
  userId: string,
  role: 'buyer' | 'seller' | 'both',
  includeArchived = false,
): Promise<ConversationSummary[]> {
  const rows = await db
    .select({
      id: conversation.id,
      listingId: conversation.listingId,
      orderId: conversation.orderId,
      buyerId: conversation.buyerId,
      sellerId: conversation.sellerId,
      subject: conversation.subject,
      status: conversation.status,
      lastMessageAt: conversation.lastMessageAt,
      buyerUnreadCount: conversation.buyerUnreadCount,
      sellerUnreadCount: conversation.sellerUnreadCount,
      createdAt: conversation.createdAt,
      listingTitle: listing.title,
      listingSlug: listing.slug,
      listingImageUrl: listingImage.url,
      otherBuyerName: sql<string>`(
        SELECT u.name FROM "user" u WHERE u.id = ${conversation.buyerId} LIMIT 1
      )`.as('other_buyer_name'),
      otherBuyerImage: sql<string | null>`(
        SELECT u.image FROM "user" u WHERE u.id = ${conversation.buyerId} LIMIT 1
      )`.as('other_buyer_image'),
      otherSellerName: sql<string>`(
        SELECT u.name FROM "user" u WHERE u.id = ${conversation.sellerId} LIMIT 1
      )`.as('other_seller_name'),
      otherSellerImage: sql<string | null>`(
        SELECT u.image FROM "user" u WHERE u.id = ${conversation.sellerId} LIMIT 1
      )`.as('other_seller_image'),
      lastMessageBody: sql<string | null>`(
        SELECT body FROM message
        WHERE conversation_id = ${conversation.id}
        ORDER BY created_at DESC LIMIT 1
      )`.as('last_message_body'),
      lastMessageSenderUserId: sql<string | null>`(
        SELECT sender_user_id FROM message
        WHERE conversation_id = ${conversation.id}
        ORDER BY created_at DESC LIMIT 1
      )`.as('last_message_sender_user_id'),
    })
    .from(conversation)
    .leftJoin(listing, eq(listing.id, conversation.listingId))
    .leftJoin(
      listingImage,
      and(eq(listingImage.listingId, conversation.listingId), eq(listingImage.isPrimary, true)),
    )
    .where(
      and(
        role === 'buyer'
          ? eq(conversation.buyerId, userId)
          : role === 'seller'
            ? eq(conversation.sellerId, userId)
            : sql`(${conversation.buyerId} = ${userId} OR ${conversation.sellerId} = ${userId})`,
        includeArchived ? undefined : not(eq(conversation.status, 'ARCHIVED')),
      ),
    )
    .orderBy(desc(conversation.lastMessageAt));

  return rows.map((row) => {
    const isBuyer = row.buyerId === userId;
    const otherPartyId = isBuyer ? row.sellerId : row.buyerId;
    const otherPartyName = isBuyer
      ? (row.otherSellerName ?? 'Unknown')
      : (row.otherBuyerName ?? 'Unknown');
    const otherPartyImage = isBuyer ? row.otherSellerImage : row.otherBuyerImage;
    const unreadCount = isBuyer ? row.buyerUnreadCount : row.sellerUnreadCount;
    const rawPreview = row.lastMessageBody ?? null;

    return {
      id: row.id,
      listingId: row.listingId,
      orderId: row.orderId,
      otherPartyId,
      otherPartyName,
      otherPartyImage: otherPartyImage ?? null,
      listingTitle: row.listingTitle ?? null,
      listingSlug: row.listingSlug ?? null,
      listingImageUrl: row.listingImageUrl ?? null,
      subject: row.subject,
      status: row.status,
      lastMessageAt: row.lastMessageAt,
      unreadCount,
      createdAt: row.createdAt,
      lastMessagePreview: rawPreview !== null ? rawPreview.slice(0, 120) : null,
      lastMessageSenderIsMe: row.lastMessageSenderUserId === userId,
    };
  });
}

export {
  getConversationMessages,
  getUnreadCount,
  getConversationForListing,
} from './messaging-detail';
