/**
 * Messaging detail queries — conversation detail and utility lookups.
 * Split from messaging.ts to stay under 300 lines.
 */

import { db } from '@twicely/db';
import {
  conversation,
  message as messageTable,
  listing,
  listingImage,
  user,
} from '@twicely/db/schema';
import { eq, and, not, sum, asc } from 'drizzle-orm';
import type { ConversationDetail, MessageItem } from './messaging';

export type { ConversationDetail, MessageItem };

/**
 * Get a conversation with all its messages. Returns null for non-participants.
 * Accepts optional onBehalfOfSellerId to allow delegated seller staff access.
 */
export async function getConversationMessages(
  conversationId: string,
  userId: string,
  onBehalfOfSellerId?: string | null,
): Promise<{ conversation: ConversationDetail; messages: MessageItem[] } | null> {
  const [conv] = await db
    .select({
      id: conversation.id,
      listingId: conversation.listingId,
      orderId: conversation.orderId,
      buyerId: conversation.buyerId,
      sellerId: conversation.sellerId,
      subject: conversation.subject,
      status: conversation.status,
      isFlagged: conversation.isFlagged,
      createdAt: conversation.createdAt,
      listingTitle: listing.title,
      listingSlug: listing.slug,
      listingPriceCents: listing.priceCents,
      listingImageUrl: listingImage.url,
    })
    .from(conversation)
    .leftJoin(listing, eq(listing.id, conversation.listingId))
    .leftJoin(
      listingImage,
      and(eq(listingImage.listingId, conversation.listingId), eq(listingImage.isPrimary, true)),
    )
    .where(eq(conversation.id, conversationId))
    .limit(1);

  if (!conv) return null;

  // Participant check — direct participant or delegated seller staff
  const isParticipant =
    conv.buyerId === userId ||
    conv.sellerId === userId ||
    (onBehalfOfSellerId != null && conv.sellerId === onBehalfOfSellerId);
  if (!isParticipant) return null;

  const isBuyerViewing = conv.buyerId === userId;
  const otherPartyId = isBuyerViewing ? conv.sellerId : conv.buyerId;

  const [otherPartyRow] = await db
    .select({ name: user.name, image: user.image })
    .from(user)
    .where(eq(user.id, otherPartyId))
    .limit(1);

  const msgRows = await db
    .select({
      id: messageTable.id,
      senderUserId: messageTable.senderUserId,
      senderName: user.name,
      body: messageTable.body,
      attachments: messageTable.attachments,
      isRead: messageTable.isRead,
      readAt: messageTable.readAt,
      isAutoGenerated: messageTable.isAutoGenerated,
      createdAt: messageTable.createdAt,
    })
    .from(messageTable)
    .innerJoin(user, eq(user.id, messageTable.senderUserId))
    .where(eq(messageTable.conversationId, conversationId))
    .orderBy(asc(messageTable.createdAt));

  return {
    conversation: {
      id: conv.id,
      listingId: conv.listingId,
      orderId: conv.orderId,
      buyerId: conv.buyerId,
      sellerId: conv.sellerId,
      subject: conv.subject,
      status: conv.status,
      isFlagged: conv.isFlagged,
      createdAt: conv.createdAt,
      listingTitle: conv.listingTitle ?? null,
      listingSlug: conv.listingSlug ?? null,
      listingPriceCents: conv.listingPriceCents ?? null,
      listingImageUrl: conv.listingImageUrl ?? null,
      otherPartyId,
      otherPartyName: otherPartyRow?.name ?? 'Unknown',
      otherPartyImage: otherPartyRow?.image ?? null,
    },
    messages: msgRows.map((r) => ({
      id: r.id,
      senderUserId: r.senderUserId,
      senderName: r.senderName,
      body: r.body,
      attachments: r.attachments,
      isRead: r.isRead,
      readAt: r.readAt,
      isAutoGenerated: r.isAutoGenerated,
      createdAt: r.createdAt,
    })),
  };
}

/**
 * Get total unread counts for a user across all non-archived conversations.
 */
export async function getUnreadCount(
  userId: string,
): Promise<{ buyerUnread: number; sellerUnread: number; total: number }> {
  const [buyerRow] = await db
    .select({ total: sum(conversation.buyerUnreadCount) })
    .from(conversation)
    .where(
      and(
        eq(conversation.buyerId, userId),
        not(eq(conversation.status, 'ARCHIVED')),
      ),
    );

  const [sellerRow] = await db
    .select({ total: sum(conversation.sellerUnreadCount) })
    .from(conversation)
    .where(
      and(
        eq(conversation.sellerId, userId),
        not(eq(conversation.status, 'ARCHIVED')),
      ),
    );

  const buyerUnread = Number(buyerRow?.total ?? 0);
  const sellerUnread = Number(sellerRow?.total ?? 0);

  return {
    buyerUnread,
    sellerUnread,
    total: buyerUnread + sellerUnread,
  };
}

/**
 * Find existing conversation for a buyer-listing pair.
 * Returns conversation ID if found and OPEN, null otherwise.
 * Used by listing detail "Message seller" button (Decision #38).
 */
export async function getConversationForListing(
  listingId: string,
  buyerId: string,
): Promise<string | null> {
  const [row] = await db
    .select({ id: conversation.id, status: conversation.status })
    .from(conversation)
    .where(
      and(
        eq(conversation.listingId, listingId),
        eq(conversation.buyerId, buyerId),
      ),
    )
    .limit(1);

  if (!row || row.status !== 'OPEN') return null;

  return row.id;
}
