import { db } from '@twicely/db';
import {
  conversation,
  message as messageTable,
  listing,
  listingImage,
  user,
} from '@twicely/db/schema';
import { eq, and, not, sql, desc, asc, sum } from 'drizzle-orm';

// ─── Return Types ─────────────────────────────────────────────────────────────

export interface ConversationSummary {
  id: string;
  listingId: string | null;
  orderId: string | null;
  otherPartyId: string;
  otherPartyName: string;
  otherPartyImage: string | null;
  listingTitle: string | null;
  listingSlug: string | null;
  listingImageUrl: string | null;
  subject: string | null;
  status: 'OPEN' | 'READ_ONLY' | 'ARCHIVED';
  lastMessageAt: Date | null;
  unreadCount: number;
  createdAt: Date;
  /** First 120 chars of the most recent message body, or null if no messages. */
  lastMessagePreview: string | null;
  /** True when the last message was sent by the requesting user. */
  lastMessageSenderIsMe: boolean;
}

export interface ConversationDetail {
  id: string;
  listingId: string | null;
  orderId: string | null;
  buyerId: string;
  sellerId: string;
  subject: string | null;
  status: 'OPEN' | 'READ_ONLY' | 'ARCHIVED';
  isFlagged: boolean;
  createdAt: Date;
  listingTitle: string | null;
  listingSlug: string | null;
  listingPriceCents: number | null;
  listingImageUrl: string | null;
  otherPartyId: string;
  otherPartyName: string;
  otherPartyImage: string | null;
}

export interface MessageItem {
  id: string;
  senderUserId: string;
  senderName: string;
  body: string;
  attachments: string[];
  isRead: boolean;
  readAt: Date | null;
  isAutoGenerated: boolean;
  createdAt: Date;
}

// ─── Queries ──────────────────────────────────────────────────────────────────

/**
 * Get conversations for a user ordered by lastMessageAt DESC.
 * Excludes ARCHIVED by default.
 */
export async function getConversations(
  userId: string,
  role: 'buyer' | 'seller' | 'both',
  includeArchived = false,
): Promise<ConversationSummary[]> {
  const rows = await db
    .select({
      id: conversation.id,
      listingId: conversation.listingId,
      orderId: conversation.orderId,
      buyerId: conversation.buyerId,
      sellerId: conversation.sellerId,
      subject: conversation.subject,
      status: conversation.status,
      lastMessageAt: conversation.lastMessageAt,
      buyerUnreadCount: conversation.buyerUnreadCount,
      sellerUnreadCount: conversation.sellerUnreadCount,
      createdAt: conversation.createdAt,
      listingTitle: listing.title,
      listingSlug: listing.slug,
      listingImageUrl: listingImage.url,
      otherBuyerName: sql<string>`(
        SELECT u.name FROM "user" u WHERE u.id = ${conversation.buyerId} LIMIT 1
      )`.as('other_buyer_name'),
      otherBuyerImage: sql<string | null>`(
        SELECT u.image FROM "user" u WHERE u.id = ${conversation.buyerId} LIMIT 1
      )`.as('other_buyer_image'),
      otherSellerName: sql<string>`(
        SELECT u.name FROM "user" u WHERE u.id = ${conversation.sellerId} LIMIT 1
      )`.as('other_seller_name'),
      otherSellerImage: sql<string | null>`(
        SELECT u.image FROM "user" u WHERE u.id = ${conversation.sellerId} LIMIT 1
      )`.as('other_seller_image'),
      lastMessageBody: sql<string | null>`(
        SELECT body FROM message
        WHERE conversation_id = ${conversation.id}
        ORDER BY created_at DESC LIMIT 1
      )`.as('last_message_body'),
      lastMessageSenderUserId: sql<string | null>`(
        SELECT sender_user_id FROM message
        WHERE conversation_id = ${conversation.id}
        ORDER BY created_at DESC LIMIT 1
      )`.as('last_message_sender_user_id'),
    })
    .from(conversation)
    .leftJoin(listing, eq(listing.id, conversation.listingId))
    .leftJoin(
      listingImage,
      and(eq(listingImage.listingId, conversation.listingId), eq(listingImage.isPrimary, true)),
    )
    .where(
      and(
        role === 'buyer'
          ? eq(conversation.buyerId, userId)
          : role === 'seller'
            ? eq(conversation.sellerId, userId)
            : sql`(${conversation.buyerId} = ${userId} OR ${conversation.sellerId} = ${userId})`,
        includeArchived ? undefined : not(eq(conversation.status, 'ARCHIVED')),
      ),
    )
    .orderBy(desc(conversation.lastMessageAt));

  return rows.map((row) => {
    const isBuyer = row.buyerId === userId;
    const otherPartyId = isBuyer ? row.sellerId : row.buyerId;
    const otherPartyName = isBuyer
      ? (row.otherSellerName ?? 'Unknown')
      : (row.otherBuyerName ?? 'Unknown');
    const otherPartyImage = isBuyer ? row.otherSellerImage : row.otherBuyerImage;
    const unreadCount = isBuyer ? row.buyerUnreadCount : row.sellerUnreadCount;

    const rawPreview = row.lastMessageBody ?? null;
    const lastMessagePreview = rawPreview !== null ? rawPreview.slice(0, 120) : null;
    const lastMessageSenderIsMe = row.lastMessageSenderUserId === userId;

    return {
      id: row.id,
      listingId: row.listingId,
      orderId: row.orderId,
      otherPartyId,
      otherPartyName,
      otherPartyImage: otherPartyImage ?? null,
      listingTitle: row.listingTitle ?? null,
      listingSlug: row.listingSlug ?? null,
      listingImageUrl: row.listingImageUrl ?? null,
      subject: row.subject,
      status: row.status,
      lastMessageAt: row.lastMessageAt,
      unreadCount,
      createdAt: row.createdAt,
      lastMessagePreview,
      lastMessageSenderIsMe,
    };
  });
}

/**
 * Get a conversation with all its messages. Returns null for non-participants.
 * Accepts optional onBehalfOfSellerId to allow delegated seller staff access.
 */
export async function getConversationMessages(
  conversationId: string,
  userId: string,
  onBehalfOfSellerId?: string | null,
): Promise<{ conversation: ConversationDetail; messages: MessageItem[] } | null> {
  const [conv] = await db
    .select({
      id: conversation.id,
      listingId: conversation.listingId,
      orderId: conversation.orderId,
      buyerId: conversation.buyerId,
      sellerId: conversation.sellerId,
      subject: conversation.subject,
      status: conversation.status,
      isFlagged: conversation.isFlagged,
      createdAt: conversation.createdAt,
      listingTitle: listing.title,
      listingSlug: listing.slug,
      listingPriceCents: listing.priceCents,
      listingImageUrl: listingImage.url,
    })
    .from(conversation)
    .leftJoin(listing, eq(listing.id, conversation.listingId))
    .leftJoin(
      listingImage,
      and(eq(listingImage.listingId, conversation.listingId), eq(listingImage.isPrimary, true)),
    )
    .where(eq(conversation.id, conversationId))
    .limit(1);

  if (!conv) return null;

  // Participant check — direct participant or delegated seller staff
  const isParticipant =
    conv.buyerId === userId ||
    conv.sellerId === userId ||
    (onBehalfOfSellerId != null && conv.sellerId === onBehalfOfSellerId);
  if (!isParticipant) return null;

  const isBuyerViewing = conv.buyerId === userId;
  const otherPartyId = isBuyerViewing ? conv.sellerId : conv.buyerId;

  const [otherPartyRow] = await db
    .select({ name: user.name, image: user.image })
    .from(user)
    .where(eq(user.id, otherPartyId))
    .limit(1);

  const msgRows = await db
    .select({
      id: messageTable.id,
      senderUserId: messageTable.senderUserId,
      senderName: user.name,
      body: messageTable.body,
      attachments: messageTable.attachments,
      isRead: messageTable.isRead,
      readAt: messageTable.readAt,
      isAutoGenerated: messageTable.isAutoGenerated,
      createdAt: messageTable.createdAt,
    })
    .from(messageTable)
    .innerJoin(user, eq(user.id, messageTable.senderUserId))
    .where(eq(messageTable.conversationId, conversationId))
    .orderBy(asc(messageTable.createdAt));

  return {
    conversation: {
      id: conv.id,
      listingId: conv.listingId,
      orderId: conv.orderId,
      buyerId: conv.buyerId,
      sellerId: conv.sellerId,
      subject: conv.subject,
      status: conv.status,
      isFlagged: conv.isFlagged,
      createdAt: conv.createdAt,
      listingTitle: conv.listingTitle ?? null,
      listingSlug: conv.listingSlug ?? null,
      listingPriceCents: conv.listingPriceCents ?? null,
      listingImageUrl: conv.listingImageUrl ?? null,
      otherPartyId,
      otherPartyName: otherPartyRow?.name ?? 'Unknown',
      otherPartyImage: otherPartyRow?.image ?? null,
    },
    messages: msgRows.map((r) => ({
      id: r.id,
      senderUserId: r.senderUserId,
      senderName: r.senderName,
      body: r.body,
      attachments: r.attachments,
      isRead: r.isRead,
      readAt: r.readAt,
      isAutoGenerated: r.isAutoGenerated,
      createdAt: r.createdAt,
    })),
  };
}

/**
 * Get total unread counts for a user across all non-archived conversations.
 */
export async function getUnreadCount(
  userId: string,
): Promise<{ buyerUnread: number; sellerUnread: number; total: number }> {
  const [buyerRow] = await db
    .select({ total: sum(conversation.buyerUnreadCount) })
    .from(conversation)
    .where(
      and(
        eq(conversation.buyerId, userId),
        not(eq(conversation.status, 'ARCHIVED')),
      ),
    );

  const [sellerRow] = await db
    .select({ total: sum(conversation.sellerUnreadCount) })
    .from(conversation)
    .where(
      and(
        eq(conversation.sellerId, userId),
        not(eq(conversation.status, 'ARCHIVED')),
      ),
    );

  const buyerUnread = Number(buyerRow?.total ?? 0);
  const sellerUnread = Number(sellerRow?.total ?? 0);

  return {
    buyerUnread,
    sellerUnread,
    total: buyerUnread + sellerUnread,
  };
}

/**
 * Find existing conversation for a buyer-listing pair.
 * Returns conversation ID if found and OPEN, null otherwise.
 * Used by listing detail "Message seller" button (Decision #38).
 */
export async function getConversationForListing(
  listingId: string,
  buyerId: string,
): Promise<string | null> {
  const [row] = await db
    .select({ id: conversation.id, status: conversation.status })
    .from(conversation)
    .where(
      and(
        eq(conversation.listingId, listingId),
        eq(conversation.buyerId, buyerId),
      ),
    )
    .limit(1);

  if (!row || row.status !== 'OPEN') return null;

  return row.id;
}
