import { SHIPPING_QUOTE_TEMPLATES } from './templates-shipping-quote';
import { POST_ORDER_TEMPLATES } from './templates-post-order';
import { LOCAL_TEMPLATES } from './templates-local';
import { AFFILIATE_TEMPLATES } from './templates-affiliate';
import { CROSSLISTER_TEMPLATES } from './templates-crosslister';
import { ENFORCEMENT_TEMPLATES } from './templates-enforcement';
import { TAX_TEMPLATES } from './templates-tax';
import { KYC_TEMPLATES } from './templates-kyc';
import { PRIVACY_TEMPLATES } from './templates-privacy';
import { HELPDESK_TEMPLATES } from './templates-helpdesk';
import { AUTHENTICATION_TEMPLATES } from './templates-authentication';
import { ACCOUNTING_TEMPLATES } from './templates-accounting';
import type { TemplateKey, TemplateDef } from './templates-types';

export type { TemplateKey, NotificationPriority, NotificationChannel, TemplateDef } from './templates-types';

export const TEMPLATES: Record<TemplateKey, TemplateDef> = {
  'offer.declined': {
    key: 'offer.declined',
    name: 'Offer Declined',
    category: 'offers',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your offer on {{itemTitle}} was not accepted',
    bodyTemplate: 'Your offer of {{offerAmountFormatted}} on {{itemTitle}} was not accepted. Your payment hold has been released.',
  },
  'offer.accepted': {
    key: 'offer.accepted',
    name: 'Offer Accepted',
    category: 'offers',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your offer on {{itemTitle}} was accepted!',
    bodyTemplate: 'Great news! Your offer of {{offerAmountFormatted}} on {{itemTitle}} has been accepted.',
  },
  'offer.received': {
    key: 'offer.received',
    name: 'Offer Received',
    category: 'offers',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'New offer on {{itemTitle}}: {{offerAmountFormatted}}',
    bodyTemplate: 'You have a new offer of {{offerAmountFormatted}} on {{itemTitle}}. Review and respond before it expires.',
  },
  'offer.countered': {
    key: 'offer.countered',
    name: 'Offer Countered',
    category: 'offers',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Counter offer on {{itemTitle}}: {{counterAmountFormatted}}',
    bodyTemplate: 'You received a counter offer of {{counterAmountFormatted}} on {{itemTitle}}.',
  },
  'offer.expired': {
    key: 'offer.expired',
    name: 'Offer Expired',
    category: 'offers',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your offer on {{itemTitle}} has expired',
    bodyTemplate: 'Your offer of {{offerAmountFormatted}} on {{itemTitle}} has expired. Your payment hold has been released.',
  },
  'order.confirmed': {
    key: 'order.confirmed',
    name: 'Order Confirmed',
    category: 'orders',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Order confirmed: {{orderNumber}}',
    bodyTemplate: 'Your order {{orderNumber}} has been confirmed. Total: {{totalFormatted}}',
  },
  'order.shipped': {
    key: 'order.shipped',
    name: 'Order Shipped',
    category: 'orders',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your order {{orderNumber}} has shipped!',
    bodyTemplate: 'Your order {{orderNumber}} is on its way.',
  },
  'order.delivered': {
    key: 'order.delivered',
    name: 'Order Delivered',
    category: 'orders',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your order {{orderNumber}} has been delivered',
    bodyTemplate: 'Your order {{orderNumber}} has been delivered. Enjoy your purchase!',
  },
  'order.canceled': {
    key: 'order.canceled',
    name: 'Order Canceled',
    category: 'orders',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Order {{orderNumber}} has been canceled',
    bodyTemplate: 'Order {{orderNumber}} has been canceled. {{cancelReason}}',
  },
  'order.refunded': {
    key: 'order.refunded',
    name: 'Order Refunded',
    category: 'orders',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Order {{orderNumber}} has been refunded',
    bodyTemplate: 'A refund of {{refundAmountFormatted}} has been issued for order {{orderNumber}}.',
  },
  'watchlist.price_drop': {
    key: 'watchlist.price_drop',
    name: 'Price Drop Alert',
    category: 'watchlist',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Price drop on {{itemTitle}}!',
    bodyTemplate: '{{itemTitle}} dropped from {{oldPriceFormatted}} to {{newPriceFormatted}}.',
  },
  'watchlist.watcher_offer': {
    key: 'watchlist.watcher_offer',
    name: 'Special Offer for Watchers',
    category: 'watchlist',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Special price on {{itemTitle}} you\'re watching!',
    bodyTemplate: 'The seller is offering you a special price of {{discountedPriceFormatted}} (was {{originalPriceFormatted}}) on {{itemTitle}}. This offer expires soon!',
  },
  'price_alert.triggered': {
    key: 'price_alert.triggered',
    name: 'Price Alert Triggered',
    category: 'price_alerts',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Price alert: {{itemTitle}} is now {{newPriceFormatted}}',
    bodyTemplate: '{{alertMessage}}',
  },
  'price_alert.back_in_stock': {
    key: 'price_alert.back_in_stock',
    name: 'Back In Stock Alert',
    category: 'price_alerts',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: '{{itemTitle}} is back in stock!',
    bodyTemplate: 'Good news! {{itemTitle}} is available again at {{newPriceFormatted}}.',
  },
  'search.new_match': {
    key: 'search.new_match',
    name: 'New Listing Match',
    category: 'search',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'New listing in {{categoryName}}!',
    bodyTemplate: 'A new item matching your alert was just listed: {{itemTitle}}.',
  },
  'subscription.trial_ending': {
    key: 'subscription.trial_ending',
    name: 'Trial Ending Soon',
    category: 'subscription',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your {{productName}} trial ends in {{daysRemaining}} days',
    bodyTemplate: 'Your free trial of {{productName}} ends on {{trialEndDate}}. Add a payment method to continue enjoying all features.',
  },
  'subscription.trial_expired': {
    key: 'subscription.trial_expired',
    name: 'Trial Expired',
    category: 'subscription',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your {{productName}} trial has ended',
    bodyTemplate: 'Your free trial of {{productName}} has ended. Upgrade now to continue accessing premium features.',
  },
  'subscription.payment_failed': {
    key: 'subscription.payment_failed',
    name: 'Subscription Payment Failed',
    category: 'subscription',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Payment failed — action required',
    bodyTemplate: 'We were unable to process your subscription payment of {{amountDue}}. Please update your payment method to keep your subscription active.',
  },
  ...POST_ORDER_TEMPLATES,
  ...SHIPPING_QUOTE_TEMPLATES,
  ...LOCAL_TEMPLATES,
  'qa.new_question': {
    key: 'qa.new_question',
    name: 'New Question on Listing',
    category: 'qa',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'New question on {{itemTitle}}',
    bodyTemplate: '{{askerName}} asked: "{{questionText}}" on your listing {{itemTitle}}.',
  },
  'qa.answer_received': {
    key: 'qa.answer_received',
    name: 'Question Answered',
    category: 'qa',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your question on {{itemTitle}} was answered',
    bodyTemplate: 'The seller answered your question on {{itemTitle}}: "{{answerText}}"',
  },
  'messaging.new_message': {
    key: 'messaging.new_message',
    name: 'New Message',
    category: 'messaging',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'New message from {{senderName}} about {{itemTitle}}',
    bodyTemplate: '{{senderName}} sent you a message about {{itemTitle}}: "{{messagePreview}}"',
  },
  'import_completed': {
    key: 'import_completed',
    name: 'Import Completed',
    category: 'crosslister',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your eBay import is complete!',
    bodyTemplate: 'Your eBay import is complete! {{createdItems}} listings imported, {{failedItems}} issues to review.',
  },
  ...CROSSLISTER_TEMPLATES,
  ...AFFILIATE_TEMPLATES,
  'social.followed_seller_new_listing': {
    key: 'social.followed_seller_new_listing',
    name: 'New Listing from Followed Seller',
    category: 'social',
    priority: 'LOW',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'New listing from {{sellerName}}',
    bodyTemplate: '{{sellerName}} listed a new item: {{listingTitle}} — {{priceFormatted}}',
  },
  ...ENFORCEMENT_TEMPLATES,
  ...TAX_TEMPLATES,
  ...KYC_TEMPLATES,
  ...PRIVACY_TEMPLATES,
  ...HELPDESK_TEMPLATES,
  ...AUTHENTICATION_TEMPLATES,
  ...ACCOUNTING_TEMPLATES,
  'seller.boostCredit.issued': {
    key: 'seller.boostCredit.issued',
    name: 'Boost Credit Issued',
    category: 'performance',
    priority: 'NORMAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'You earned {{amountFormatted}} in boost credit!',
    bodyTemplate: 'You earned {{amountFormatted}} in boost credit for {{periodMonthFormatted}} as a {{bandLabel}}. Credits are applied automatically before your paid boost budget and expire at month-end.',
  },
  'seller.payout.paid': {
    key: 'seller.payout.paid',
    name: 'Payout Sent to Bank',
    category: 'payouts',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your payout of {{amountFormatted}} was sent to your bank',
    bodyTemplate: 'Your payout of {{amountFormatted}} was sent to your bank account via Stripe. Funds typically arrive within 1–3 business days.',
  },
  'seller.payout.failed': {
    key: 'seller.payout.failed',
    name: 'Payout to Bank Failed',
    category: 'payouts',
    priority: 'CRITICAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your payout could not be sent to your bank',
    bodyTemplate: 'Your payout of {{amountFormatted}} could not be sent. Reason: {{failureReason}}. Please check your bank account details in your payout settings.',
  },
} as Record<TemplateKey, TemplateDef>;

/** Simple template interpolation: replace {{key}} with data[key] */
export function interpolate(template: string, data: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => data[key] ?? '');
}
