import type { TemplateDef } from './templates-types';

export const HELPDESK_TEMPLATES: Record<string, TemplateDef> = {
  'helpdesk.case.created': {
    key: 'helpdesk.case.created',
    name: 'Case Created Confirmation',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Support case {{caseNumber}} received — {{subject}}',
    bodyTemplate: 'We have received your support request ({{caseNumber}}). Our team will respond within {{slaTarget}}. You can track your case at {{caseUrl}}.',
  },
  'helpdesk.case.auto_reply': {
    key: 'helpdesk.case.auto_reply',
    name: 'Auto-Reply with Case Number',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL'],
    subjectTemplate: 'Re: {{subject}} [{{caseNumber}}]',
    bodyTemplate: 'Thank you for contacting Twicely Support. Your case {{caseNumber}} has been received. While you wait, these articles may help: {{suggestedArticles}}. Reply to this email to add information to your case.',
  },
  'helpdesk.case.agent_reply': {
    key: 'helpdesk.case.agent_reply',
    name: 'Agent Replied to Case',
    category: 'helpdesk',
    priority: 'HIGH',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Re: {{subject}} [{{caseNumber}}]',
    bodyTemplate: '{{agentName}} from Twicely Support replied to your case {{caseNumber}}. View the full reply at {{caseUrl}}.',
  },
  'helpdesk.case.resolved': {
    key: 'helpdesk.case.resolved',
    name: 'Case Resolved',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your support case {{caseNumber}} has been resolved',
    bodyTemplate: 'Your support case {{caseNumber}} has been marked as resolved. If you have further questions, you can reopen it within {{reopenWindowDays}} days at {{caseUrl}}.',
  },
  'helpdesk.case.closed': {
    key: 'helpdesk.case.closed',
    name: 'Case Auto-Closed',
    category: 'helpdesk',
    priority: 'LOW',
    defaultChannels: ['EMAIL'],
    subjectTemplate: 'Support case {{caseNumber}} has been closed',
    bodyTemplate: 'Your support case {{caseNumber}} has been automatically closed. If you need further assistance, please open a new case at {{contactUrl}}.',
  },
  'helpdesk.case.reopened': {
    key: 'helpdesk.case.reopened',
    name: 'Case Reopened by User',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Re: {{subject}} [{{caseNumber}}] — Reopened',
    bodyTemplate: 'Case {{caseNumber}} has been reopened. Our team will review your latest message shortly.',
  },
  'helpdesk.csat.request': {
    key: 'helpdesk.csat.request',
    name: 'CSAT Survey Request',
    category: 'helpdesk',
    priority: 'LOW',
    defaultChannels: ['EMAIL'],
    subjectTemplate: 'How did we do? Rate your support experience',
    bodyTemplate: 'Your case {{caseNumber}} was recently resolved. We would appreciate your feedback on your experience. Rate us at {{csatUrl}}.',
  },
  'helpdesk.agent.assigned': {
    key: 'helpdesk.agent.assigned',
    name: 'Agent Assigned to Case',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'Case {{caseNumber}} assigned to you',
    bodyTemplate: 'You have been assigned to case {{caseNumber}}: {{subject}} ({{priority}} priority). View the case at {{caseUrl}}.',
  },
  'helpdesk.agent.sla_warning': {
    key: 'helpdesk.agent.sla_warning',
    name: 'SLA Warning',
    category: 'helpdesk',
    priority: 'HIGH',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'SLA warning: Case {{caseNumber}} due in {{timeRemaining}}',
    bodyTemplate: 'Case {{caseNumber}} ({{subject}}) is approaching its SLA deadline. {{timeRemaining}} remaining before breach.',
  },
  'helpdesk.agent.sla_breach': {
    key: 'helpdesk.agent.sla_breach',
    name: 'SLA Breached',
    category: 'helpdesk',
    priority: 'CRITICAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'SLA BREACHED: Case {{caseNumber}}',
    bodyTemplate: 'Case {{caseNumber}} ({{subject}}) has breached its SLA. Immediate action required.',
  },
  'helpdesk.agent.mention': {
    key: 'helpdesk.agent.mention',
    name: 'Agent Mentioned in Note',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: '{{mentionedBy}} mentioned you in case {{caseNumber}}',
    bodyTemplate: '{{mentionedBy}} mentioned you in an internal note on case {{caseNumber}}: {{subject}}.',
  },
  'helpdesk.case.watcher_update': {
    key: 'helpdesk.case.watcher_update',
    name: 'Case Watcher Update',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['IN_APP'],
    subjectTemplate: 'Update on watched case {{caseNumber}}',
    bodyTemplate: '{{eventDescription}} on case {{caseNumber}} ({{subject}}). View the case at {{caseUrl}}.',
  },
  'helpdesk.case.status_changed_user': {
    key: 'helpdesk.case.status_changed_user',
    name: 'Case Status Changed (User Notification)',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your support case {{caseNumber}} status updated',
    bodyTemplate: 'Your support case {{caseNumber}} ({{subject}}) status has been updated to {{statusLabel}}. View your case at {{caseUrl}}.',
  },
  'helpdesk.case.escalated_user': {
    key: 'helpdesk.case.escalated_user',
    name: 'Case Escalated (User Notification)',
    category: 'helpdesk',
    priority: 'NORMAL',
    defaultChannels: ['EMAIL', 'IN_APP'],
    subjectTemplate: 'Your support case {{caseNumber}} has been escalated',
    bodyTemplate: 'Your support case {{caseNumber}} ({{subject}}) has been escalated for review by our senior team. We will be in touch shortly.',
  },
};
