import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── Mocks ────────────────────────────────────────────────────────────────────

vi.mock('@twicely/db', () => ({
  db: { select: vi.fn(), insert: vi.fn(), update: vi.fn() },
}));

vi.mock('@twicely/db/schema', () => ({
  message: {
    id: 'id',
    conversationId: 'conversation_id',
    senderUserId: 'sender_user_id',
    isAutoGenerated: 'is_auto_generated',
    createdAt: 'created_at',
  },
  sellerProfile: {
    userId: 'user_id',
    vacationMode: 'vacation_mode',
    vacationAutoReplyMessage: 'vacation_auto_reply_message',
    vacationStartAt: 'vacation_start_at',
    vacationEndAt: 'vacation_end_at',
  },
  conversation: {
    id: 'id',
    buyerUnreadCount: 'buyer_unread_count',
  },
}));

import { db } from '@twicely/db';
import { sendVacationAutoReply } from '../vacation-auto-reply';

const CONV_ID = 'conv-001';
const SELLER_ID = 'seller-001';
const BUYER_ID = 'buyer-001';

const mockDbSelect = vi.mocked(db.select);
const mockDbInsert = vi.mocked(db.insert);
const mockDbUpdate = vi.mocked(db.update);

function makeSellerChain(sp: unknown) {
  const chain = {
    from: vi.fn(),
    where: vi.fn(),
    limit: vi.fn().mockResolvedValue(sp ? [sp] : []),
  };
  chain.from.mockReturnValue(chain);
  chain.where.mockReturnValue(chain);
  return chain;
}

function makeAutoReplyCheckChain(rows: unknown[]) {
  const chain = {
    from: vi.fn(),
    where: vi.fn(),
    limit: vi.fn().mockResolvedValue(rows),
  };
  chain.from.mockReturnValue(chain);
  chain.where.mockReturnValue(chain);
  return chain;
}

function makeInsertChain() {
  return { values: vi.fn().mockResolvedValue([]) };
}

function makeUpdateChain() {
  const chain = { set: vi.fn() };
  chain.set.mockReturnValue({ where: vi.fn().mockResolvedValue([]) });
  return chain;
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('sendVacationAutoReply', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockDbInsert.mockReturnValue(makeInsertChain() as never);
    mockDbUpdate.mockReturnValue(makeUpdateChain() as never);
  });

  it('does NOT send auto-reply when seller is the sender', async () => {
    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, SELLER_ID);

    expect(result.sent).toBe(false);
    expect(mockDbSelect).not.toHaveBeenCalled();
  });

  it('does NOT send auto-reply when seller is not on vacation', async () => {
    mockDbSelect.mockReturnValueOnce(makeSellerChain({ vacationMode: false }) as never);

    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, BUYER_ID);

    expect(result.sent).toBe(false);
    expect(mockDbInsert).not.toHaveBeenCalled();
  });

  it('does NOT send auto-reply when seller profile not found', async () => {
    mockDbSelect.mockReturnValueOnce(makeSellerChain(null) as never);

    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, BUYER_ID);

    expect(result.sent).toBe(false);
    expect(mockDbInsert).not.toHaveBeenCalled();
  });

  it('does NOT send auto-reply if one already exists in current vacation period', async () => {
    mockDbSelect
      .mockReturnValueOnce(makeSellerChain({
        vacationMode: true,
        vacationAutoReplyMessage: 'Away on vacation',
        vacationStartAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        vacationEndAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      }) as never)
      .mockReturnValueOnce(makeAutoReplyCheckChain([{ id: 'msg-existing' }]) as never);

    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, BUYER_ID);

    expect(result.sent).toBe(false);
    expect(mockDbInsert).not.toHaveBeenCalled();
  });

  it('sends auto-reply with seller custom message when on vacation and no prior reply', async () => {
    const customMessage = 'I am on vacation, back soon!';
    mockDbSelect
      .mockReturnValueOnce(makeSellerChain({
        vacationMode: true,
        vacationAutoReplyMessage: customMessage,
        vacationStartAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        vacationEndAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      }) as never)
      .mockReturnValueOnce(makeAutoReplyCheckChain([]) as never);

    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, BUYER_ID);

    expect(result.sent).toBe(true);
    expect(mockDbInsert).toHaveBeenCalledTimes(1);
    expect(mockDbUpdate).toHaveBeenCalledTimes(1);

    const insertValues = vi.mocked(mockDbInsert.mock.results[0]?.value.values).mock.calls[0]?.[0] as Record<string, unknown>;
    expect(insertValues?.body).toBe(customMessage);
    expect(insertValues?.isAutoGenerated).toBe(true);
    expect(insertValues?.senderUserId).toBe(SELLER_ID);
  });

  it('uses default message when autoReplyMessage is null', async () => {
    const returnDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    mockDbSelect
      .mockReturnValueOnce(makeSellerChain({
        vacationMode: true,
        vacationAutoReplyMessage: null,
        vacationStartAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        vacationEndAt: returnDate,
      }) as never)
      .mockReturnValueOnce(makeAutoReplyCheckChain([]) as never);

    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, BUYER_ID);

    expect(result.sent).toBe(true);
    const insertValues = vi.mocked(mockDbInsert.mock.results[0]?.value.values).mock.calls[0]?.[0] as Record<string, unknown>;
    expect(typeof insertValues?.body).toBe('string');
    expect(insertValues?.body).toContain("away until");
  });

  it('uses fallback default message when autoReplyMessage is empty string', async () => {
    mockDbSelect
      .mockReturnValueOnce(makeSellerChain({
        vacationMode: true,
        vacationAutoReplyMessage: '   ',  // whitespace only
        vacationStartAt: null,
        vacationEndAt: null,
      }) as never)
      .mockReturnValueOnce(makeAutoReplyCheckChain([]) as never);

    const result = await sendVacationAutoReply(CONV_ID, SELLER_ID, BUYER_ID, BUYER_ID);

    expect(result.sent).toBe(true);
    const insertValues = vi.mocked(mockDbInsert.mock.results[0]?.value.values).mock.calls[0]?.[0] as Record<string, unknown>;
    expect(typeof insertValues?.body).toBe('string');
    expect(insertValues?.body).toContain("away");
  });
});
