/**
 * Auto-message helper for local meetup events (G2.6).
 *
 * Posts system messages to the conversation linked to an order
 * when key local transaction events occur (BOTH_CHECKED_IN, NO_SHOW).
 */

import { db } from '@twicely/db';
import { conversation, message } from '@twicely/db/schema';
import { eq } from 'drizzle-orm';
import { createId } from '@paralleldrive/cuid2';
import { logger } from '@twicely/logger';

const AUTO_MESSAGE_BODIES: Record<
  'BOTH_CHECKED_IN' | 'NO_SHOW',
  (context: { locationName?: string; noShowParty?: string }) => string
> = {
  BOTH_CHECKED_IN: ({ locationName }) => {
    const location = locationName ? ` at ${locationName}` : '';
    return `Both parties have checked in${location}. You can now complete the transaction.`;
  },
  NO_SHOW: ({ noShowParty }) => {
    const party = noShowParty ?? 'One party';
    return `${party} did not check in for the scheduled meetup. If you need help, contact Twicely Support.`;
  },
};

/**
 * Post a system message to the conversation linked to a local order.
 *
 * @param orderId - The order.id to find the linked conversation
 * @param messageType - Event type driving the auto-message
 * @param context - Optional display context (locationName, noShowParty)
 */
export async function sendLocalAutoMessage(
  orderId: string,
  messageType: 'BOTH_CHECKED_IN' | 'NO_SHOW',
  context: { locationName?: string; noShowParty?: string },
): Promise<void> {
  try {
    const [conv] = await db
      .select({ id: conversation.id, buyerId: conversation.buyerId })
      .from(conversation)
      .where(eq(conversation.orderId, orderId))
      .limit(1);

    if (!conv) {
      logger.warn('[local-auto-messages] No conversation found for order', { orderId });
      return;
    }

    const bodyFn = AUTO_MESSAGE_BODIES[messageType];
    const body = bodyFn(context);

    await db.insert(message).values({
      id: createId(),
      conversationId: conv.id,
      senderUserId: conv.buyerId, // system messages attributed to buyerId — kept internal
      body,
      isAutoGenerated: true,
    });

    logger.info('[local-auto-messages] Auto-message sent', { orderId, messageType });
  } catch (err) {
    logger.error('[local-auto-messages] Error posting auto-message', {
      orderId,
      messageType,
      error: String(err),
    });
  }
}
