import { pgTable, text, integer, boolean, timestamp, index, uniqueIndex } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { createId } from '@paralleldrive/cuid2';
import { conversationStatusEnum } from './enums';
import { user } from './auth';
import { listing } from './listings';
import { order } from './commerce';

// §9.1 conversation
export const conversation = pgTable('conversation', {
  id:              text('id').primaryKey().$defaultFn(() => createId()),
  // set null: conversation history kept even if listing/order is deleted
  listingId:       text('listing_id').references(() => listing.id, { onDelete: 'set null' }),
  orderId:         text('order_id').references(() => order.id, { onDelete: 'set null' }),
  // restrict: conversation must survive buyer deletion for moderation audit trail
  buyerId:         text('buyer_id').notNull().references(() => user.id, { onDelete: 'restrict' }),
  sellerId:        text('seller_id').notNull(),
  subject:         text('subject'),
  status:          conversationStatusEnum('status').notNull().default('OPEN'),
  lastMessageAt:   timestamp('last_message_at', { withTimezone: true }),
  buyerUnreadCount: integer('buyer_unread_count').notNull().default(0),
  sellerUnreadCount: integer('seller_unread_count').notNull().default(0),
  isFlagged:       boolean('is_flagged').notNull().default(false),
  flagReason:      text('flag_reason'),
  createdAt:       timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt:       timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  buyerIdx:        index('conv_buyer').on(table.buyerId, table.lastMessageAt),
  sellerIdx:       index('conv_seller').on(table.sellerId, table.lastMessageAt),
  listingIdx:      index('conv_listing').on(table.listingId),
  orderIdx:        index('conv_order').on(table.orderId),
  // R1 (hub-messaging audit): dedup (buyerId, sellerId, listingId) at the DB
  // level to prevent race conditions in concurrent createConversationAndSend
  // calls. Application-level SELECT-then-INSERT dedup is race-unsafe.
  uniqueTriple:    uniqueIndex('conv_unique_triple').on(table.buyerId, table.sellerId, table.listingId),
}));

// §9.2 message
export const message = pgTable('message', {
  id:              text('id').primaryKey().$defaultFn(() => createId()),
  conversationId:  text('conversation_id').notNull().references(() => conversation.id, { onDelete: 'cascade' }),
  // restrict: messages are communication records — must survive user deletion for moderation
  senderUserId:    text('sender_user_id').notNull().references(() => user.id, { onDelete: 'restrict' }),
  body:            text('body').notNull(),
  attachments:     text('attachments').array().notNull().default(sql`'{}'::text[]`),
  isRead:          boolean('is_read').notNull().default(false),
  readAt:          timestamp('read_at', { withTimezone: true }),
  isAutoGenerated: boolean('is_auto_generated').notNull().default(false),
  createdAt:       timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  conversationIdx: index('msg_conversation').on(table.conversationId, table.createdAt),
}));
