'use client';

import { useRef, useEffect, useState, useTransition, useCallback } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { ArrowLeft, AlertTriangle, Lock, MoreHorizontal } from 'lucide-react';
import { Avatar, AvatarFallback, AvatarImage } from '@twicely/ui/avatar';
import { Badge } from '@twicely/ui/badge';
import { Button } from '@twicely/ui/button';
import { Textarea } from '@twicely/ui/textarea';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@twicely/ui/dropdown-menu';
import { formatDate, formatPrice } from '@twicely/utils/format';
import { cn } from '@twicely/utils/cn';
import { MessageComposer } from './message-composer';
import { TypingIndicator } from './typing-indicator';
import { archiveConversation, reportMessage } from '@/lib/actions/messaging-manage';
import { useConversationRealtime } from '@/hooks/use-conversation-realtime';
import type { ConversationDetail, MessageItem } from '@/lib/queries/messaging';

interface ConversationThreadProps {
  conversation: ConversationDetail;
  messages: MessageItem[];
  currentUserId: string;
}

const TEMP_ID_PREFIX = 'temp-';
const DEDUP_WINDOW_MS = 5000;

export function ConversationThread({ conversation, messages: initialMessages, currentUserId }: ConversationThreadProps) {
  const router = useRouter();
  const scrollRef = useRef<HTMLDivElement>(null);
  const [, startArchiveTransition] = useTransition();
  const [showReportForm, setShowReportForm] = useState(false);
  const [reportReason, setReportReason] = useState('');
  const [reportError, setReportError] = useState<string | null>(null);
  const [isSubmittingReport, startReportTransition] = useTransition();
  const [messages, setMessages] = useState<MessageItem[]>(initialMessages);
  const [typingUserId, setTypingUserId] = useState<string | null>(null);
  const typingTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight });
  }, [messages]);

  const clearTypingTimeout = useCallback(() => {
    if (typingTimeoutRef.current) clearTimeout(typingTimeoutRef.current);
    typingTimeoutRef.current = setTimeout(() => setTypingUserId(null), 3000);
  }, []);

  const handleNewMessage = useCallback((msg: MessageItem) => {
    setMessages((prev) => {
      const now = Date.now();
      const matchIndex = prev.findIndex((m) =>
        m.id.startsWith(TEMP_ID_PREFIX) &&
        m.senderUserId === msg.senderUserId &&
        m.body === msg.body &&
        now - new Date(m.createdAt).getTime() < DEDUP_WINDOW_MS
      );
      if (matchIndex !== -1) {
        const updated = [...prev];
        updated[matchIndex] = msg;
        return updated;
      }
      return [...prev, msg];
    });
  }, []);

  const handleTyping = useCallback((userId: string) => {
    setTypingUserId(userId); clearTypingTimeout();
  }, [clearTypingTimeout]);

  useConversationRealtime({
    conversationId: conversation.id,
    currentUserId,
    onNewMessage: handleNewMessage,
    onTyping: handleTyping,
  });

  // Optimistic message on send
  const handleMessageSent = useCallback((msg: { body: string; attachments: string[] }) => {
    const optimistic: MessageItem = {
      id: `${TEMP_ID_PREFIX}${Date.now()}`,
      senderUserId: currentUserId,
      senderName: 'You',
      body: msg.body,
      attachments: msg.attachments,
      isRead: false,
      readAt: null,
      isAutoGenerated: false,
      createdAt: new Date(),
    };
    setMessages((prev) => [...prev, optimistic]);
  }, [currentUserId]);

  // Determine last read own message for read receipt
  let lastReadOwnMessageId: string | null = null;
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg && msg.senderUserId === currentUserId && !msg.isAutoGenerated && msg.isRead) {
      lastReadOwnMessageId = msg.id;
      break;
    }
  }

  // Find last non-system message for report
  let lastNonSystemMessageId: string | null = null;
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    if (msg && !msg.isAutoGenerated && !msg.id.startsWith(TEMP_ID_PREFIX)) {
      lastNonSystemMessageId = msg.id;
      break;
    }
  }

  const otherInitials = conversation.otherPartyName
    .split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);

  const handleArchive = () => {
    startArchiveTransition(async () => {
      const result = await archiveConversation({ conversationId: conversation.id });
      if (result.success) {
        router.push('/my/messages');
      }
    });
  };

  const handleReport = () => {
    if (!reportReason.trim() || reportReason.trim().length < 5 || !lastNonSystemMessageId) return;
    setReportError(null);
    startReportTransition(async () => {
      const result = await reportMessage({ messageId: lastNonSystemMessageId!, reason: reportReason.trim() });
      if (result.success) {
        setShowReportForm(false);
        setReportReason('');
      } else {
        setReportError(result.error ?? 'Failed to report message');
      }
    });
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center gap-3 border-b px-4 py-3 bg-white">
        <Link href="/my/messages" className="text-gray-500 hover:text-gray-700">
          <ArrowLeft className="h-5 w-5" />
          <span className="sr-only">Back to messages</span>
        </Link>
        <Avatar className="h-8 w-8 shrink-0">
          <AvatarImage src={conversation.otherPartyImage ?? undefined} alt={conversation.otherPartyName} />
          <AvatarFallback className="text-xs">{otherInitials}</AvatarFallback>
        </Avatar>
        <div className="flex-1 min-w-0">
          <p className="font-semibold text-sm truncate">{conversation.otherPartyName}</p>
          {conversation.orderId && (
            <Badge variant="secondary" className="text-xs mt-0.5">Order linked</Badge>
          )}
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <button type="button" className="p-1.5 text-gray-400 hover:text-gray-600" aria-label="Conversation options">
              <MoreHorizontal className="h-4 w-4" />
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {conversation.status !== 'ARCHIVED' && (
              <DropdownMenuItem onClick={handleArchive}>
                Archive conversation
              </DropdownMenuItem>
            )}
            {conversation.status === 'OPEN' && lastNonSystemMessageId && (
              <DropdownMenuItem onClick={() => setShowReportForm((v) => !v)}>
                Report message
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      {/* Inline report form */}
      {showReportForm && (
        <div className="border-b bg-red-50 px-4 py-3 space-y-2">
          <p className="text-sm font-medium text-red-700">Report this message</p>
          {reportError && <p className="text-xs text-red-600">{reportError}</p>}
          <Textarea
            value={reportReason}
            onChange={(e) => setReportReason(e.target.value)}
            placeholder="Describe the issue (min 5 characters)"
            rows={2}
            maxLength={500}
            className="resize-none text-sm"
            disabled={isSubmittingReport}
          />
          <div className="flex gap-2">
            <Button size="sm" onClick={handleReport} disabled={isSubmittingReport || reportReason.trim().length < 5}>
              Submit report
            </Button>
            <Button size="sm" variant="outline" onClick={() => { setShowReportForm(false); setReportError(null); }}>
              Cancel
            </Button>
          </div>
        </div>
      )}

      {/* Listing context card */}
      {conversation.listingSlug && (
        <div className="border-b bg-gray-50 px-4 py-3">
          <Link href={`/i/${conversation.listingSlug}`} className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            {conversation.listingImageUrl && (
              <Image src={conversation.listingImageUrl} alt={conversation.listingTitle ?? 'Listing'} width={56} height={56} className="rounded object-cover h-14 w-14 shrink-0" />
            )}
            <div className="min-w-0">
              <p className="text-sm font-medium truncate">{conversation.listingTitle}</p>
              {conversation.listingPriceCents !== null && (
                <p className="text-sm text-gray-600">{formatPrice(conversation.listingPriceCents)}</p>
              )}
              <p className="text-xs text-primary">View listing</p>
            </div>
          </Link>
        </div>
      )}

      {/* Off-platform warning */}
      {conversation.isFlagged && (
        <div className="flex items-center gap-2 bg-yellow-50 border-b border-yellow-200 px-4 py-2">
          <AlertTriangle className="h-4 w-4 text-yellow-600 shrink-0" />
          <p className="text-sm text-yellow-800">For your protection, complete transactions on Twicely.</p>
        </div>
      )}

      {/* Message list */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {messages.map((msg) => {
          const isOwn = msg.senderUserId === currentUserId;
          const isSystem = msg.isAutoGenerated;
          const showReadReceipt = isOwn && !isSystem && msg.id === lastReadOwnMessageId && msg.isRead;

          if (isSystem) {
            return (
              <div key={msg.id} className="flex justify-center">
                <div className="bg-muted/50 rounded-lg px-4 py-2 max-w-sm text-center">
                  <p className="text-xs text-muted-foreground italic">{msg.body}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{formatDate(msg.createdAt, 'relative')}</p>
                </div>
              </div>
            );
          }

          return (
            <div key={msg.id} className={cn('flex', isOwn ? 'justify-end' : 'justify-start')}>
              {!isOwn && (
                <Avatar className="h-7 w-7 mr-2 shrink-0 self-end">
                  <AvatarFallback className="text-xs">{msg.senderName.charAt(0).toUpperCase()}</AvatarFallback>
                </Avatar>
              )}
              <div className={cn('max-w-[70%]', isOwn ? 'text-right' : 'text-left')}>
                <p className="text-xs text-muted-foreground mb-0.5">{msg.senderName}</p>
                <div className={cn('rounded-lg px-3 py-2 text-sm', isOwn ? 'bg-primary/10 text-gray-900' : 'bg-muted text-gray-900')}>
                  {msg.body}
                </div>
                <p className="text-xs text-gray-400 mt-0.5">{formatDate(msg.createdAt, 'relative')}</p>
                {showReadReceipt && (
                  <p className="text-xs text-gray-400 mt-0.5">Read</p>
                )}
              </div>
              {isOwn && (
                <Avatar className="h-7 w-7 ml-2 shrink-0 self-end">
                  <AvatarFallback className="text-xs">{msg.senderName.charAt(0).toUpperCase()}</AvatarFallback>
                </Avatar>
              )}
            </div>
          );
        })}
        <TypingIndicator visible={typingUserId !== null && conversation.status === 'OPEN'} />
      </div>

      {/* Compose or closed banner */}
      {conversation.status === 'OPEN' ? (
        <MessageComposer conversationId={conversation.id} onMessageSent={handleMessageSent} />
      ) : (
        <div className="border-t bg-gray-50 px-4 py-3 flex items-center gap-2">
          <Lock className="h-4 w-4 text-gray-400 shrink-0" />
          <p className="text-sm text-gray-500">This conversation is closed.</p>
        </div>
      )}
    </div>
  );
}
