import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { platformSetting, conversation, message as messageTable } from '../schema';
import { USER_IDS } from './seed-users';
import { LISTING_IDS } from './seed-listings';

// Hardcoded IDs for idempotency
const CONV_IDS = {
  c1: 'seed-conv-001',
  c2: 'seed-conv-002',
  c3: 'seed-conv-003',
};

const MSG_IDS = {
  m1a: 'seed-msg-001a',
  m1b: 'seed-msg-001b',
  m2a: 'seed-msg-002a',
  m2b: 'seed-msg-002b',
  m2c: 'seed-msg-002c',
  m3a: 'seed-msg-003a',
  m3b: 'seed-msg-003b',
};

/**
 * Seed comms.messaging.* platform settings and demo conversations.
 */
export async function seedMessaging(db: PostgresJsDatabase): Promise<void> {
  const now = new Date();
  const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);

  // 1. Platform settings (4 comms.messaging.* keys per Platform Settings Canonical Section 12.5)
  await db
    .insert(platformSetting)
    .values([
      {
        key: 'comms.messaging.enabled',
        value: true,
        type: 'boolean',
        category: 'comms',
        description: 'Master switch for buyer-seller messaging',
      },
      {
        key: 'comms.messaging.rateLimitPerHour',
        value: 30,
        type: 'number',
        category: 'comms',
        description: 'Maximum messages a user can send per hour (Feature Lock-In S19)',
      },
      {
        key: 'comms.messaging.moderationEnabled',
        value: true,
        type: 'boolean',
        category: 'comms',
        description: 'Enable off-platform detection and flagging',
      },
      {
        key: 'comms.messaging.autoResponseEnabled',
        value: true,
        type: 'boolean',
        category: 'comms',
        description: 'Enable auto-generated system messages (order/shipping events)',
      },
    ])
    .onConflictDoNothing();

  // 2. Conversation 1: buyer1 asks seller1 about listing (2 messages, both read)
  await db
    .insert(conversation)
    .values({
      id: CONV_IDS.c1,
      listingId: LISTING_IDS[4],
      buyerId: USER_IDS.buyer1,
      sellerId: USER_IDS.seller1,
      subject: 'MacBook Pro 16" M2 — Question',
      status: 'OPEN',
      lastMessageAt: daysAgo(1),
      buyerUnreadCount: 0,
      sellerUnreadCount: 0,
      isFlagged: false,
      flagReason: null,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    })
    .onConflictDoNothing();

  await db
    .insert(messageTable)
    .values([
      {
        id: MSG_IDS.m1a,
        conversationId: CONV_IDS.c1,
        senderUserId: USER_IDS.buyer1,
        body: 'Hi, does the MacBook Pro still have warranty left? And does it include the original box?',
        attachments: [],
        isRead: true,
        readAt: daysAgo(2),
        isAutoGenerated: false,
        createdAt: daysAgo(3),
      },
      {
        id: MSG_IDS.m1b,
        conversationId: CONV_IDS.c1,
        senderUserId: USER_IDS.seller1,
        body: 'Yes! It has 8 months of AppleCare remaining and comes with the original box, all cables, and documentation.',
        attachments: [],
        isRead: true,
        readAt: daysAgo(1),
        isAutoGenerated: false,
        createdAt: daysAgo(2),
      },
    ])
    .onConflictDoNothing();

  // 3. Conversation 2: buyer2 and seller1 exchange about an order (3 messages, 1 unread for buyer)
  await db
    .insert(conversation)
    .values({
      id: CONV_IDS.c2,
      listingId: LISTING_IDS[0],
      buyerId: USER_IDS.buyer2,
      sellerId: USER_IDS.seller1,
      subject: 'iPhone 15 Pro Max — Shipping question',
      status: 'OPEN',
      lastMessageAt: daysAgo(0),
      buyerUnreadCount: 1,
      sellerUnreadCount: 0,
      isFlagged: false,
      flagReason: null,
      createdAt: daysAgo(5),
      updatedAt: daysAgo(0),
    })
    .onConflictDoNothing();

  await db
    .insert(messageTable)
    .values([
      {
        id: MSG_IDS.m2a,
        conversationId: CONV_IDS.c2,
        senderUserId: USER_IDS.buyer2,
        body: 'Can you ship to Canada? What shipping method do you use?',
        attachments: [],
        isRead: true,
        readAt: daysAgo(4),
        isAutoGenerated: false,
        createdAt: daysAgo(5),
      },
      {
        id: MSG_IDS.m2b,
        conversationId: CONV_IDS.c2,
        senderUserId: USER_IDS.seller1,
        body: 'I ship internationally via USPS Priority Mail International. Delivery is typically 7-14 business days to Canada.',
        attachments: [],
        isRead: true,
        readAt: daysAgo(3),
        isAutoGenerated: false,
        createdAt: daysAgo(4),
      },
      {
        id: MSG_IDS.m2c,
        conversationId: CONV_IDS.c2,
        senderUserId: USER_IDS.seller1,
        body: 'Also happy to include a tracking number as soon as I ship. Let me know if you want to proceed!',
        attachments: [],
        isRead: false,
        readAt: null,
        isAutoGenerated: false,
        createdAt: daysAgo(0),
      },
    ])
    .onConflictDoNothing();

  // 4. Conversation 3: flagged conversation with off-platform keyword
  await db
    .insert(conversation)
    .values({
      id: CONV_IDS.c3,
      listingId: LISTING_IDS[27],
      buyerId: USER_IDS.buyer3,
      sellerId: USER_IDS.seller2,
      subject: 'Nike Air Jordan 1 — Deal outside platform',
      status: 'OPEN',
      lastMessageAt: daysAgo(1),
      buyerUnreadCount: 0,
      sellerUnreadCount: 1,
      isFlagged: true,
      flagReason: 'Off-platform transaction detected',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
    })
    .onConflictDoNothing();

  await db
    .insert(messageTable)
    .values([
      {
        id: MSG_IDS.m3a,
        conversationId: CONV_IDS.c3,
        senderUserId: USER_IDS.buyer3,
        body: 'Love the shoes! Are you open to PayPal payment to save on fees?',
        attachments: [],
        isRead: true,
        readAt: daysAgo(1),
        isAutoGenerated: false,
        createdAt: daysAgo(2),
      },
      {
        id: MSG_IDS.m3b,
        conversationId: CONV_IDS.c3,
        senderUserId: USER_IDS.seller2,
        body: 'Sorry, I only transact through Twicely to keep things safe for both of us. The buyer protection is worth it!',
        attachments: [],
        isRead: false,
        readAt: null,
        isAutoGenerated: false,
        createdAt: daysAgo(1),
      },
    ])
    .onConflictDoNothing();
}
