import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { category } from '../schema';

// Hardcoded IDs for idempotency
export const CATEGORY_IDS = {
  // Top-level
  electronics: 'seed-cat-electronics',
  apparel: 'seed-cat-apparel',
  home: 'seed-cat-home',
  collectibles: 'seed-cat-collectibles',
  // Leaf - Electronics
  phones: 'seed-cat-phones-tablets',
  computers: 'seed-cat-computers-laptops',
  cameras: 'seed-cat-cameras-photo',
  // Leaf - Apparel
  womens: 'seed-cat-womens-clothing',
  mens: 'seed-cat-mens-clothing',
  shoes: 'seed-cat-shoes-sneakers',
  // Leaf - Home
  kitchen: 'seed-cat-kitchen-dining',
  furniture: 'seed-cat-furniture',
  garden: 'seed-cat-garden-outdoor',
  // Leaf - Collectibles
  tradingCards: 'seed-cat-trading-cards',
  watches: 'seed-cat-watches-jewelry',
  handbags: 'seed-cat-designer-handbags',
};

/**
 * Seed categories (16 total: 4 top-level + 12 leaf).
 * Depends on seedSystem() running first (needs staff user).
 */
export async function seedCategories(db: PostgresJsDatabase): Promise<void> {
  // Top-level categories (4)
  await db.insert(category).values([
    {
      id: CATEGORY_IDS.electronics,
      slug: 'electronics',
      name: 'Electronics',
      description: 'Electronics, gadgets, and tech',
      feeBucket: 'ELECTRONICS',
      sortOrder: 0,
      isActive: true,
      isLeaf: false,
      depth: 0,
      path: 'electronics',
    },
    {
      id: CATEGORY_IDS.apparel,
      slug: 'apparel-accessories',
      name: 'Apparel & Accessories',
      description: 'Clothing, shoes, and accessories',
      feeBucket: 'APPAREL_ACCESSORIES',
      sortOrder: 1,
      isActive: true,
      isLeaf: false,
      depth: 0,
      path: 'apparel-accessories',
    },
    {
      id: CATEGORY_IDS.home,
      slug: 'home-garden',
      name: 'Home & Garden',
      description: 'Home decor, furniture, and garden',
      feeBucket: 'HOME_GENERAL',
      sortOrder: 2,
      isActive: true,
      isLeaf: false,
      depth: 0,
      path: 'home-garden',
    },
    {
      id: CATEGORY_IDS.collectibles,
      slug: 'collectibles-luxury',
      name: 'Collectibles & Luxury',
      description: 'Collectibles, watches, and luxury items',
      feeBucket: 'COLLECTIBLES_LUXURY',
      sortOrder: 3,
      isActive: true,
      isLeaf: false,
      depth: 0,
      path: 'collectibles-luxury',
    },
  ]).onConflictDoNothing();

  // Leaf categories (12)
  await db.insert(category).values([
    // Electronics leaves
    {
      id: CATEGORY_IDS.phones,
      slug: 'phones-tablets',
      parentId: CATEGORY_IDS.electronics,
      name: 'Phones & Tablets',
      feeBucket: 'ELECTRONICS',
      sortOrder: 0,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'electronics.phones-tablets',
    },
    {
      id: CATEGORY_IDS.computers,
      slug: 'computers-laptops',
      parentId: CATEGORY_IDS.electronics,
      name: 'Computers & Laptops',
      feeBucket: 'ELECTRONICS',
      sortOrder: 1,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'electronics.computers-laptops',
    },
    {
      id: CATEGORY_IDS.cameras,
      slug: 'cameras-photo',
      parentId: CATEGORY_IDS.electronics,
      name: 'Cameras & Photo',
      feeBucket: 'ELECTRONICS',
      sortOrder: 2,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'electronics.cameras-photo',
    },
    // Apparel leaves
    {
      id: CATEGORY_IDS.womens,
      slug: 'womens-clothing',
      parentId: CATEGORY_IDS.apparel,
      name: "Women's Clothing",
      feeBucket: 'APPAREL_ACCESSORIES',
      sortOrder: 0,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'apparel-accessories.womens-clothing',
    },
    {
      id: CATEGORY_IDS.mens,
      slug: 'mens-clothing',
      parentId: CATEGORY_IDS.apparel,
      name: "Men's Clothing",
      feeBucket: 'APPAREL_ACCESSORIES',
      sortOrder: 1,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'apparel-accessories.mens-clothing',
    },
    {
      id: CATEGORY_IDS.shoes,
      slug: 'shoes-sneakers',
      parentId: CATEGORY_IDS.apparel,
      name: 'Shoes & Sneakers',
      feeBucket: 'APPAREL_ACCESSORIES',
      sortOrder: 2,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'apparel-accessories.shoes-sneakers',
    },
    // Home leaves
    {
      id: CATEGORY_IDS.kitchen,
      slug: 'kitchen-dining',
      parentId: CATEGORY_IDS.home,
      name: 'Kitchen & Dining',
      feeBucket: 'HOME_GENERAL',
      sortOrder: 0,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'home-garden.kitchen-dining',
    },
    {
      id: CATEGORY_IDS.furniture,
      slug: 'furniture',
      parentId: CATEGORY_IDS.home,
      name: 'Furniture',
      feeBucket: 'HOME_GENERAL',
      sortOrder: 1,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'home-garden.furniture',
    },
    {
      id: CATEGORY_IDS.garden,
      slug: 'garden-outdoor',
      parentId: CATEGORY_IDS.home,
      name: 'Garden & Outdoor',
      feeBucket: 'HOME_GENERAL',
      sortOrder: 2,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'home-garden.garden-outdoor',
    },
    // Collectibles leaves
    {
      id: CATEGORY_IDS.tradingCards,
      slug: 'trading-cards',
      parentId: CATEGORY_IDS.collectibles,
      name: 'Trading Cards',
      feeBucket: 'COLLECTIBLES_LUXURY',
      sortOrder: 0,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'collectibles-luxury.trading-cards',
    },
    {
      id: CATEGORY_IDS.watches,
      slug: 'watches-jewelry',
      parentId: CATEGORY_IDS.collectibles,
      name: 'Watches & Jewelry',
      feeBucket: 'COLLECTIBLES_LUXURY',
      sortOrder: 1,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'collectibles-luxury.watches-jewelry',
    },
    {
      id: CATEGORY_IDS.handbags,
      slug: 'designer-handbags',
      parentId: CATEGORY_IDS.collectibles,
      name: 'Designer Handbags',
      feeBucket: 'COLLECTIBLES_LUXURY',
      sortOrder: 2,
      isActive: true,
      isLeaf: true,
      depth: 1,
      path: 'collectibles-luxury.designer-handbags',
    },
  ]).onConflictDoNothing();
}
