export const SUBJECTS = [
  'Listing',
  'Order',
  'Cart',
  'Shipment',
  'ShippingProfile',
  'Return',
  'Dispute',
  'Payout',
  'LedgerEntry',
  'Review',
  'ReviewResponse',
  'Offer',
  'Message',
  'Conversation',
  'HelpdeskCase',
  'Notification',
  'User',
  'SellerProfile',
  'DelegatedAccess',
  'Subscription',
  'Promotion',
  'PromotedListing',
  'Category',
  'Policy',
  'FeatureFlag',
  'AuditEvent',
  'Setting',
  'Analytics',
  'HealthCheck',
  'AuthenticationRequest',
  'CombinedShippingQuote',
  'StaffUser',
  'CustomRole',
  'Expense',
  'FinancialReport',
  'MileageEntry',
  'ListingQuestion',
  'Watchlist',
  'BrowsingHistory',
  // Crosslister — E2.1
  'CrosslisterAccount',
  'ChannelProjection',
  'CrossJob',
  'ImportBatch',
  'AutomationSetting',
  // Admin settings — F1
  'Module',
  'ProviderAdapter',
  'ProviderInstance',
  'ProviderUsageMapping',
  'ProviderHealthLog',
  // Affiliate program — G1.2
  'Affiliate',
  'Referral',
  'PromoCode',
  'AffiliateCommission',
  'AffiliatePayout',
  // Local transactions — G2.1
  'LocalTransaction',
  'SafeMeetupLocation',
  // Local reliability — G2.8
  'LocalReliabilityEvent',
  // Local fraud detection — G2.15
  'LocalFraudFlag',
  // Curation -- G3.10
  'CuratedCollection',
  // Enforcement -- G4
  'ContentReport',
  'EnforcementAction',
  // Tax & Compliance -- G5
  'TaxInfo',
  // Identity Verification + Privacy -- G6
  'IdentityVerification',
  'DataExportRequest',
  'DataRetention',
  // Finance -- I3
  'Chargeback',
  'Hold',
  // Helpdesk & KB -- G9
  'KbArticle',
  'KbCategory',
  'HelpdeskTeam',
  'HelpdeskTeamMember',
  'HelpdeskMacro',
  'HelpdeskSavedView',
  'HelpdeskRoutingRule',
  'HelpdeskSlaPolicy',
  'HelpdeskAutomationRule',
  'HelpdeskEmailConfig',
  'CaseCsat',
  // Trust & Safety — I7
  'TrustSafety',
  'SecurityEvent',
  // Accounting integrations — G10.3
  'AccountingIntegration',
  // FraudCase — deferred until fraud_case table exists
] as const;

export type Subject = (typeof SUBJECTS)[number];
